### ISSUE TITLE
The app is not developed in the open

### ISSUE THREAD

**Issue by ViktarStarastsenka** [flathub/flathub#5229] opened 2024-05-10 14:32 UTC
Redis Insight is marked as "This app is not developed in the open, so only its developers know how it works.".
However, its repository is public - https://github.com/RedisInsight/RedisInsight.

**Comment by hfiguiere** [comment] 2024-05-10 14:34
if only you mentionned WHICH app that is on Flathub we could establish why.

**Comment by razzeee** [comment] 2024-05-10 14:36
https://flathub.org/apps/com.redis.RedisInsight

**Comment by razzeee** [comment] 2024-05-10 14:36
It's due to the license here https://github.com/flathub/com.redis.RedisInsight/blob/master/com.redis.RedisInsight.metainfo.xml#L9

**Comment by bbhtt** [comment] 2024-05-10 14:37
SSPL is not a free license according to OSI/FSF, hence it is marked as proprietary.

**Comment by ViktarStarastsenka** [comment] 2024-05-10 14:43
I understand about the license, but this statement is not true for Redis Insight. Everyone can see the code.

`This app is not developed in the open, so only its developers know how it works. It may be insecure in ways that are hard to detect, and it may change without oversight.`

**Comment by hfiguiere** [comment] 2024-05-10 14:46
Also it's a binary repack so we can't even reproduce the build from source.

**Comment by bbhtt** [comment] 2024-05-10 14:47
You can open an issue in https://github.com/flathub-infra/website/issues for that. Maybe the wording could be changed a bit.

Appstream doesn't distinguish between source available but non free and source available/proprietary licenses. It's either free or non-free from appstream's perspective. So it might be hard to show selective text based on the license type. Maybe it can be changed to something generic.

**Comment by bbhtt** [comment] 2024-05-10 15:05
It shows a separate wording:

![image](https://github.com/flathub/flathub/assets/62639087/a7eb6808-6c7d-4ae9-b3c3-afa34c10467c)

Contrast to zoom:

![image](https://github.com/flathub/flathub/assets/62639087/d4b1de4c-33b4-4bb5-bd44-c1c420392bcd)

It has some special cases. It shows the second wording only when it is literally `Licenseref-proprietary`.

If it is not free software license and not `Licenseref-proprietary` literally then it is marked as a `special license`.

**Comment by razzeee** [comment] 2024-05-12 13:34
This should be quiet similar to what g-s does https://github.com/flathub-infra/website/pull/3179

**Closed** 2024-05-13 02:10 UTC
Labels: website
