### ISSUE TITLE
End of life run times ! But, flatpak did not shows me what use them ?!

### ISSUE THREAD

**Issue by Nokia808** [flathub/flathub#2518] opened 2021-09-19 09:11 UTC
Hello ! 

New versions of flatpak show which package uses end of life run time within end of life output. But today, it did not show me which package(s) used them !

Kindly see bellow outputs:

```
$ flatpak update
Looking for updates…
Info: org.freedesktop.Platform.VAAPI.Intel//19.08 is end-of-life, with reason:
   The Freedesktop SDK 19.08 runtime is no longer supported as of September 1, 2021. Please ask your application developer to migrate to a supported version
Info: org.freedesktop.Platform.GL.default//19.08 is end-of-life, with reason:
   The Freedesktop SDK 19.08 runtime is no longer supported as of September 1, 2021. Please ask your application developer to migrate to a supported version


        ID                                   Branch Op Remote  Download
        ID                                              Branch            Op           Remote            Download
 1. [✓] org.freedesktop.Platform.GL.default             19.08             u            flathub           14.7 kB / 89.1 MB
 2. [✓] org.freedesktop.Platform.VAAPI.Intel            19.08             u            flathub            3.0 kB / 8.7 MB
 3. [✓] com.getferdi.Ferdi                              stable            u            flathub            1.5 MB / 120.6 MB

Updates complete.

```

```
$ flatpak update
Looking for updates…
Info: org.freedesktop.Platform.VAAPI.Intel//19.08 is end-of-life, with reason:
   The Freedesktop SDK 19.08 runtime is no longer supported as of September 1, 2021. Please ask your application developer to migrate to a supported version
Info: org.freedesktop.Platform.GL.default//19.08 is end-of-life, with reason:
   The Freedesktop SDK 19.08 runtime is no longer supported as of September 1, 2021. Please ask your application developer to migrate to a supported version
Nothing to do.

```

```
$ flatpak uninstall --unused
Nothing unused to uninstall

```

As you see, I run "flatpak uninstall --unused" & it showed me nothing !

My flatpak version is 1.10.2

**Comment by hfiguiere** [comment] 2021-09-19 12:51
if you try to uninstall the runtime it will tell you. but basically the apps need to be updated.

**Comment by Nokia808** [comment] 2021-09-19 14:59
@hfiguiere 
This is the output when I tried to remove run time:

```
$ flatpak uninstall org.freedesktop.Platform.VAAPI.Intel//19.08


        ID                                            Branch         Op
 1.     org.freedesktop.Platform.VAAPI.Intel          19.08          r

Proceed with these changes to the system installation? [Y/n]: n
```


```
$ flatpak uninstall org.freedesktop.Platform.GL.default//19.08


        ID                                           Branch          Op
 1.     org.freedesktop.Platform.GL.default          19.08           r

Proceed with these changes to the system installation? [Y/n]: n

```

I aborted ..........

As you see, they did not show me what you expected !!! Is this a bug ?!

**Comment by haggen88** [comment] 2021-09-19 16:28
I have the same issue here [flatpak 1.10.2]. I checked my apps in "flatpak list" and I checked with "flatpak info << App ID >>"  but I don't have any application that uses these unsupported runtimes/sdk. I don't know what the message is about.

**Comment by vchernin** [comment] 2021-09-21 04:50
Please paste the output of `flatpak list`. I have found this to happen when you have some other runtime or SDK that is outdated.

**Comment by haggen88** [comment] 2021-09-21 05:13
![q](https://user-images.githubusercontent.com/68134588/134114393-2504ee98-2c31-4b2c-8c81-796802bedb67.png)

In my case I only had one app [Melodia / Melody] that had the outdated Runtime and SDK [Runtime: org.gnome.Platform / x86_64 / 3.36 - Sdk: org.gnome.Sdk / x86_64 / 3.36].

I have no idea where the problem comes from with org.freedesktop.Platform.VAAPI.Intel // 19.08 and org.freedesktop.Platform.GL.default // 19.08, I recently updated and I get this issue. 

![qq](https://user-images.githubusercontent.com/68134588/134114364-4329b1a5-7bb0-46a1-ac8f-516cd1e744b7.png)

**Comment by vchernin** [comment] 2021-09-21 05:16
I think it's likely Melodia/Melody is the cause here. Can you try removing it, and then removing the GNOME 3.36 runtime, and then running `flatpak update` again.

I see someone has already updated [Melody's runtime](https://github.com/flathub/com.github.artemanufrij.playmymusic/pull/12) but no one merged it...

**Comment by hfiguiere** [comment] 2021-09-21 05:19
I just merged it. It was apparently left behind :-(

**Comment by vchernin** [comment] 2021-09-21 05:20
> I just merged it. It was apparently left behind :-(

I'm sure there are many others which get left behind... I think Flathub needs a bot to ping people about unmerged PRs or something

**Comment by haggen88** [comment] 2021-09-21 05:22
Some time ago I reported the outdated [runtime](https://github.com/artemanufrij/playmymusic/issues/193) .... it has not been updated yet :(

**Comment by vchernin** [comment] 2021-09-21 05:24
>  it has not been updated yet 

It will be updated in ~5 hours or so from now. Then you can safely remove the 3.36 runtime without removing the app.

**Comment by Nokia808** [comment] 2021-09-21 07:28
@vchernin 

Bellow the output of "flatpak list"

```
$ flatpak list
Name           Application ID          Version             Branch Installation
InVesalius     br.gov.cti.invesalius   3.1.99995           stable system
Decoder        …m.belmoussaoui.Decoder 0.2.1               stable system
Markets        com.bitstower.Markets   0.5.2               stable system
Ferdi          com.getferdi.Ferdi      5.6.2               stable system
ScanTailor Ad… …x4.ScanTailor-Advanced v1.0.16             stable system
Dialect        ….github.gi_lom.dialect 1.3.0               stable system
eOVPN          com.github.jkotra.eovpn 1.10                stable system
Tor Browser L… …ee.torbrowser-launcher 0.3.5               stable system
Ciano          ….robertsanseries.ciano 0.2.4               stable system
AstroMenace    ….viewizard.AstroMenace 1.4.1               stable system
Shortwave      …haeckerfelix.Shortwave 2.0.1               stable system
PDF Mix Tool   eu.scarpetta.PDFMixTool 1.0.1               stable system
Metadata Clea… …vigier.MetadataCleaner 1.0.8               stable system
Jami (GNOME c… net.jami.Jami           20210819.1.be229cd2 stable system
TORCS          net.sourceforge.torcs   1.3.7               stable system
SuperTuxKart   …ertuxkart.SuperTuxKart 1.2                 stable system
Session Deskt… network.loki.Session    1.7.2               stable system
Freedesktop P… …g.freedesktop.Platform 20.08.15            20.08  system
Freedesktop P… …g.freedesktop.Platform 21.08.2             21.08  system
default        …op.Platform.GL.default                     19.08  system
Mesa           …op.Platform.GL.default 21.1.7              20.08  system
Mesa           …op.Platform.GL.default 21.2.1              21.08  system
Intel          …p.Platform.VAAPI.Intel                     19.08  system
Intel          …p.Platform.VAAPI.Intel                     20.08  system
Intel          …p.Platform.VAAPI.Intel                     21.08  system
ffmpeg-full    …p.Platform.ffmpeg-full                     21.08  system
openh264       …ktop.Platform.openh264 2.1.0               2.0    system
Monero GUI     org.getmonero.Monero    0.17.2.3            stable system
GNOME Applica… org.gnome.Platform                          40     system
Mint-Y-Dark G… ….Gtk3theme.Mint-Y-Dark                     3.22   system
Jitsi Meet     org.jitsi.jitsi-meet    2.8.12              stable system
Adwaita theme  org.kde.KStyle.Adwaita                      5.14   system
Adwaita theme  org.kde.KStyle.Adwaita                      5.15   system
KDE Applicati… org.kde.Platform                            5.14   system
KDE Applicati… org.kde.Platform                            5.15   system
Okular         org.kde.okular          21.08.1             stable system
LibreOffice    …ibreoffice.LibreOffice 7.2.1.2             stable system
nomacs - Imag… org.nomacs.ImageLounge  3.16                stable system
Telegram Desk… org.telegram.desktop    3.1                 stable system
Xonotic        org.xonotic.Xonotic     0.8.2               stable system
Backgammony    uk.jnthn.backgammony    1.0.0               stable system
i2pd           website.i2pd.i2pd       2.39.0              stable system
OpenArena      ws.openarena.OpenArena  0.8.8               stable system
```

**Comment by vchernin** [comment] 2021-09-21 07:31
@Nokia808 `flatpak remove org.kde.Platform//5.14`

If it warns you some apps depend on KDE 5.14 they should be updated.

**Comment by Nokia808** [comment] 2021-09-21 07:39
@vchernin 

The output is bellow:

```
$ flatpak remove org.kde.Platform//5.14


        ID                                            Branch         Op
 1.     org.kde.Platform                              5.14           r
 2.     org.kde.Platform.Locale                       5.14           r
 3.     org.freedesktop.Platform.GL.default           19.08          r
 4.     org.freedesktop.Platform.VAAPI.Intel          19.08          r

Proceed with these changes to the system installation? [Y/n]: n
```


What I have to do now ?!! It did not showed me that "some apps depend on DKE 5.14, but asked me to remove additional packages as you see above !!

**Comment by vchernin** [comment] 2021-09-21 07:40
You should be able to safely proceed to remove those (enter y).

If you actually need those for anything Flatpak should explicitly warn you (but it hasn't).

**Comment by Nokia808** [comment] 2021-09-21 07:46
@vchernin 

Bellow is the output of removal which end by failure:

```
$ flatpak remove org.kde.Platform//5.14


        ID                                            Branch         Op
 1. [✗] org.kde.Platform                              5.14           r
 2. [ ] org.kde.Platform.Locale                       5.14           r
 3. [ ] org.freedesktop.Platform.GL.default           19.08          r
 4. [ ] org.freedesktop.Platform.VAAPI.Intel          19.08          r

Error: Can't remove org.kde.Platform/x86_64/5.14, it is needed for: org.nomacs.ImageLounge, website.i2pd.i2pd
error: Failed to uninstall org.kde.Platform: Can't remove org.kde.Platform/x86_64/5.14, it is needed for: org.nomacs.ImageLounge, website.i2pd.i2pd
```

The i2pd is under active development, but nomacs is not updated since long time & I'm afraid that no one will respond ! - see:
https://github.com/nomacs/nomacs

**Comment by vchernin** [comment] 2021-09-21 07:51
I've opened PRs to update both app's runtimes: https://github.com/flathub/org.nomacs.ImageLounge/pull/8 and https://github.com/flathub/website.i2pd.i2pd/pull/10#issuecomment-923727345
That is the proper fix for both.

**Closed** 2021-09-27 10:40 UTC

**Comment by Nokia808** [comment] 2021-09-27 13:24
@barthalion 
I updated my system to last point but still this happened to me !!

**Comment by vchernin** [comment] 2021-09-27 16:33
@Nokia808 your system is dependent on https://github.com/flathub/org.nomacs.ImageLounge/pull/8. There isn't much else we can do other than fix that.
