### ISSUE TITLE
gnucash is stale, needs updating and also needs two (branch) offerings

### ISSUE THREAD

**Issue by cmurf** [flathub/flathub#430] opened 2018-06-11 20:18 UTC
Referencing this:
https://wiki.gnucash.org/wiki/Release_Schedule

Flathub currently installs 2.6.19, while upstream offers 2.6.21 for their "old stable" branch. And offers 3.1 for "current stable branch.

I think flathub would want to offer both branches. It's sane that users would want to stick with an old stable branch of some time for software like this. And new users are better offer with current stable branch.

**Comment by nedrichards** [comment] 2018-06-21 11:54
This is a duplicate of https://github.com/flathub/org.gnucash.GnuCash/issues/12 and similar issues.

Flathub only offers one stable branch at the moment and that's unlikely to change in the short term.

**Closed by nedrichards** 2018-06-21 11:54 UTC
