### ISSUE TITLE
Remove the `branch/nightly` branch of com.chatterino.chatterino

### ISSUE THREAD

**Issue by ilya-zlobintsev** [flathub/flathub#5081] opened 2024-03-23 16:35 UTC
Hi, I'm the maintainer of com.chatterino.chatterino, and previously I was using the flatpak branches functionality to publish nightly builds on the main flathub repository in an alternative branch.

At one point the builds for that branch stopped working, and I was told on the flatpak matrix channel that flathub will no longer allow non-standard branches.

I have since stopped updating that branch, but it still shows up when people run `flatpak install chatterino`. I would like it to be removed to avoid confusing users into installing an old build from an unmaintained branch.

**Comment by bbhtt** [comment] 2024-03-24 01:37
Duplicate of https://github.com/flathub/flathub/issues/4767, the person with access to the server is on vacation. You have to wait. It needs to be purged from the server manually.

**Closed by bbhtt** 2024-03-24 01:37 UTC

**Comment by ilya-zlobintsev** [comment] 2024-03-24 07:19
Sorry about the duplicate, completely forgot that i reported this already
