### ISSUE TITLE
Flathub builder skipping module "(no sources)"

### ISSUE THREAD

**Issue by enzo1982** [flathub/flathub#2395] opened 2021-06-27 20:17 UTC
I'm trying to update [org.freac.freac](https://github.com/flathub/org.freac.freac) to the latest release, but one module is being skipped in the build.

The [build log](https://flathub.org/builds/#/builders/28/builds/6131/steps/6/logs/stdio) says _"Skipping module libmp4v2 (no sources)"_ in line 3817. However, the module clearly has sources defined in the [manifest](https://github.com/flathub/org.freac.freac/blob/master/org.freac.freac.json#L97) and I can build this just fine using an up to date flatpak-builder locally.

I tried changing the source URL, but that didn't make a difference. Not sure what's wrong here. Would be great if someone could take a look.

It's also worrying that the build is still marked as successful, even though the resulting Flatpak is broken without the libmp4v2 module.

**Comment by enzo1982** [comment] 2021-06-28 00:38
The issue seems to be with "file" sources. The module being skipped had two "file" sources to update outdated config.guess and config.sub files included in the original source archive.

After a few tries, I replaced the "file" sources with a "patch" source that updates those files and got it to build that way.

I got a working solution now, but it would still be great if this could be fixed.

**Comment by hfiguiere** [comment] 2021-06-28 01:06
The way to update the `config.guess` and `config.sub` is to copy them like this: 
```
cp -p /usr/share/automake-*/config.{sub,guess} .
```

**Comment by arteymix** [comment] 2021-07-27 15:13
I'm experiencing a similar issue with https://github.com/flathub/org.develz.Crawl/issues/11 except I don't update config.guess nor config.sub.

**Comment by hfiguiere** [comment] 2021-07-27 15:17
> I'm experiencing a similar issue with [flathub/org.develz.Crawl#11](https://github.com/flathub/org.develz.Crawl/issues/11) except I don't update config.guess nor config.sub.

Line 8 in the logs:

"(flatpak-builder:1393053): flatpak-builder-WARNING **: 14:49:03.781: Invalid source: No slashes allowed in dest-filename"

**Comment by hfiguiere** [comment] 2021-07-27 15:19
TBF I which this was a fatal error.

**Comment by enzo1982** [comment] 2021-07-27 15:41
Thanks @hfiguiere!

So that restriction was added recently? Is there a new property to specify the destination folder for file sources? Otherwise this would limit the usefulness of file sources quite a bit.

It would indeed be helpful if that error was fatal. Or at least if it would appear near the _Skipping module ..._ line in the log. I just didn't think about checking the top of the log.

**Comment by hfiguiere** [comment] 2021-07-27 15:51
> Thanks @hfiguiere!
> 
> So that restriction was added recently? Is there a new property to specify the destination folder for file sources? Otherwise this would limit the usefulness of file sources quite a bit.

it was made a "warning" in a recent release of flatpak-builder. It was never valid.

> dest: Directory inside the source dir where this source will be extracted.

**Comment by hfiguiere** [comment] 2021-07-27 15:51
Note that if you are overwriting an upstream file, it's better to use a patch.

**Comment by arteymix** [comment] 2021-07-27 15:56
I'm testing this right now. If this is the cause, then we should make this fatal with a recommendation of using `dest` instead.

**Comment by arteymix** [comment] 2021-07-27 17:25
It works! https://flathub.org/builds/#/builders/32/builds/54522

**Comment by bbhtt** [comment] 2024-02-14 14:14
Closing per last comment then

**Closed by bbhtt** 2024-02-14 14:14 UTC

**Comment by fedelibre** [comment] 2024-04-27 14:11
I'm having the same problem and I can't understand why the sources have not been downloaded.
Look at [this build](https://buildbot.flathub.org/#/builders/7/builds/14315) and search the line:

> Skipping module guile3 (no sources)

**Comment by hfiguiere** [comment] 2024-04-27 14:19
No need to scroll down. Line 32

```
(flatpak-builder:2): Json-WARNING **: 22:48:01.671: Failed to deserialize "sources" property of type "gpointer" for an object of type "BuilderModule"
```
