### ISSUE TITLE
Unable to send signals from a D-Bus service I own

### ISSUE THREAD

**Issue by Tamaranch** [flathub/flathub#2770] opened 2022-01-14 17:22 UTC
Maybe related to https://github.com/flatpak/xdg-dbus-proxy/issues/25.

It works with `--socket=session-bus`, but I don't know what permission to add besides that to make it work. Normally there should be no need for anything since the service name derives from my application name: `org.xfce.ristretto` -> `org.xfce.ristretto.Thumbnailer1`.

But I can't update my application with `--socket=session-bus`: https://github.com/flathub/org.xfce.ristretto/pull/7
```
bwrap: Can't find source path /run/flatpak/bus: No such file or directory
```

Here is an extract of the logs when running with `--log-session-bus`:
```
C20: -> :1.129 signal org.xfce.ristretto.Thumbnailer1.Started at /org/xfce/ristretto/Thumbnailer1
*DENIED*
C21: -> :1.129 signal org.xfce.ristretto.Thumbnailer1.Ready at /org/xfce/ristretto/Thumbnailer1
*DENIED*
C22: -> :1.129 signal org.xfce.ristretto.Thumbnailer1.Ready at /org/xfce/ristretto/Thumbnailer1
*DENIED*
C23: -> :1.129 signal org.xfce.ristretto.Thumbnailer1.Ready at /org/xfce/ristretto/Thumbnailer1
*DENIED*
C24: -> :1.129 signal org.xfce.ristretto.Thumbnailer1.Ready at /org/xfce/ristretto/Thumbnailer1
*DENIED*
C25: -> :1.129 signal org.xfce.ristretto.Thumbnailer1.Ready at /org/xfce/ristretto/Thumbnailer1
*DENIED*
C26: -> :1.129 signal org.xfce.ristretto.Thumbnailer1.Ready at /org/xfce/ristretto/Thumbnailer1
*DENIED*
C27: -> :1.129 signal org.xfce.ristretto.Thumbnailer1.Ready at /org/xfce/ristretto/Thumbnailer1
*DENIED*
C28: -> :1.129 signal org.xfce.ristretto.Thumbnailer1.Ready at /org/xfce/ristretto/Thumbnailer1
*DENIED*
C29: -> :1.129 signal org.xfce.ristretto.Thumbnailer1.Ready at /org/xfce/ristretto/Thumbnailer1
*DENIED*
C30: -> :1.129 signal org.xfce.ristretto.Thumbnailer1.Ready at /org/xfce/ristretto/Thumbnailer1
*DENIED*
C31: -> :1.129 signal org.xfce.ristretto.Thumbnailer1.Finished at /org/xfce/ristretto/Thumbnailer1
*DENIED*
```

**Comment by barthalion** [comment] 2022-01-25 18:31
Please don't add `--socket=session-bus`. It's unlikely to be a solution for your problem.

The infra issue that caused said build failure has been fixed with https://github.com/flathub/org.flatpak.Builder/pull/70. As you now bundled Tumbler, is there anything actionable left?

**Comment by Tamaranch** [comment] 2022-01-25 21:29
> Please don't add `--socket=session-bus`. It's unlikely to be a solution for your problem.

This is the only real solution I have found so far. Since I couldn't get it to build on Flathub, I had to patch Ristretto itself in the meantime, to make up for Tumbler's inability to emit signals.

But that's just temporary. The real solution would be to find the appropriate permissions for Tumbler, or to fix the bug on the Flatpak side if there is one. Because I don't see why a service owned by the main application (here Ristretto) should need special permissions to emit signals.

If it's possible to set `--socket=session-bus` now, I'd be tempted to do it: it seems better than having to patch Ristretto, even if it's probably not as good from an isolation point of view.

**Comment by Tamaranch** [comment] 2022-01-25 21:58
Indeed, it builds correctly with `--socket=session-bus` now: flathub/org.xfce.ristretto#13

**Comment by gasinvein** [comment] 2022-10-23 09:30
What breaks from the UX perspective?
I don't see errors like these when just launching the app with `--socket=session-bus` perm revoked.

**Comment by Tamaranch** [comment] 2022-10-23 10:01
What breaks is thumbnail display (View -> Show Thumbnail Bar).
To get these errors, you have to run Tumbler by hand in another terminal (cleaning up first to do proper tests):
```sh
pkill tumblerd
rm -r ~/.var/app/org.xfce.ristretto/cache/thumbnails/*
/usr/bin/flatpak run --log-session-bus --branch=master --arch=x86_64 --command=/app/lib/tumbler-1/tumblerd org.xfce.ristretto
```
You will get some of these errors when you launch Ristretto, and then you will get more if you scroll the thumbnail bar. Of course you need to open a directory with enough images:
```sh
flatpak run org.xfce.ristretto ~/Images
```

**Comment by gasinvein** [comment] 2022-10-23 10:09
Hmm, this looks like flatpak/xdg-dbus-proxy#25 indeed.

**Comment by Tamaranch** [comment] 2022-10-24 10:05
@gasinvein So do you think that Ristretto could be added to the list of exceptions in #2785 until this problem is solved?

**Comment by gasinvein** [comment] 2022-10-24 10:59
It's not my call, but I personally believe this is not strong enough reason to make an exception and create a precedent.

**Comment by Tamaranch** [comment] 2022-10-24 14:52
I understand but then I don't see how I can unblock the situation for updates to Ristretto or its dependencies, as in https://github.com/flathub/org.xfce.ristretto/pull/38.

I really don't see myself tinkering with a patch on the main app to make up for the lack of a real thumbnailer. So I guess it will stay stuck in its current state for lack of anything better.

**Comment by barthalion** [comment] 2022-10-25 06:55
@Tamaranch Please add your ID to https://github.com/flathub/flatpak-builder-lint/blob/master/flatpak_builder_lint/staticfiles/exceptions.json and open a PR.

**Comment by hadess** [comment] 2022-11-07 14:31
I can't reproduce the problem using:
`flatpak run --command=bash -d --nosocket=session-bus --log-session-bus org.xfce.ristretto`

```
C66: -> org.freedesktop.portal.Desktop call org.freedesktop.portal.FileChooser.OpenFile at /org/freedesktop/portal/desktop
B63330: <- :1.73 return from C66
B63332: <- :1.73 signal org.freedesktop.portal.Request.Response at /org/freedesktop/portal/desktop/request/1_6559/gtk155685763
C67: -> :1.6551 call org.xfce.ristretto.Xfconf.SetProperty at /org/xfce/ristretto/Xfconf
B100: <- :1.6551 return from C67
C68: -> :1.6555 call org.xfce.ristretto.Thumbnailer1.Queue at /org/xfce/ristretto/Thumbnailer1
B59: <- :1.6555 return from C68
B60: <- :1.6555 signal org.xfce.ristretto.Thumbnailer1.Started at /org/xfce/ristretto/Thumbnailer1
B61: <- :1.6555 signal org.xfce.ristretto.Thumbnailer1.Ready at /org/xfce/ristretto/Thumbnailer1
B62: <- :1.6555 signal org.xfce.ristretto.Thumbnailer1.Finished at /org/xfce/ristretto/Thumbnailer1
```

I don't think that we should add exception to D-Bus access checks unless the app is explicitly a D-Bus debugging tool.

**Comment by Tamaranch** [comment] 2022-11-07 16:56
Removing permissions via `--nosocket=session-bus` is not the same as removing them in the manifest in this case, perhaps because the main application is not itself the D-Bus service.
You need to remove `--socket=session-bus` from `org.xfce.ristretto.yml` and rebuild. Then you will have the problem.
See also https://github.com/flathub/flathub/issues/2770#issuecomment-1288072496 about how to get the logs in this case.

**Comment by bbhtt** [comment] 2024-04-07 07:55
Seems solved by having an exception for org.xfce.ristretto

**Closed by bbhtt** 2024-04-07 07:55 UTC
Labels: discussion
