### ISSUE TITLE
Recently Added and Recently Updated

### ISSUE THREAD

**Issue by BeverlyCode** [flathub/flathub#4347] opened 2023-07-22 18:52 UTC
https://github.com/flathub/flathub/pull/4311#issuecomment-1646649475

> Any idea why VoxelPaint does not show up in the recently added applications on flathub.org?
> 
> Also the recently added is kinda confusing because, most of those listed seem to be recently updated not recently added? Whats going on?
> 
> Are these lists just Semi-Manually curated or something, because I can't see a real distinction between the apps listed as "Recently Updated" and "Recently Added". What exactly is the distinction? To me is seems mostly in both categories they are just updated apps.
> 
> (I think) my apps only appear in Recently Updated if I increase the version number in the appdata.xml. No idea with Recently Added though.

What is the deal with these two categories?

**Comment by razzeee** [comment] 2023-07-23 16:50
Recently added are newly added flatpaks, newly updated shows updated ones. So a typical app should only ever show one time in `recently added` but can popup multiple times in recently updated.

**Comment by barthalion** [comment] 2023-07-24 12:36
Duplicate of https://github.com/flathub/website/issues/1636.

**Closed as completed** 2023-07-24 14:31 UTC

**Comment by razzeee** [comment] 2023-07-26 22:18
It's listed in the newly added apps now :)
