### ISSUE TITLE
Flathub appstream omits <requires>/<recommends> device support data

### ISSUE THREAD

**Issue by wjt** [flathub/flathub#2439] opened 2021-07-28 20:04 UTC
Yesterday I added some device support metadata to Flathub's appstream https://github.com/flathub/org.tuxpaint.Tuxpaint/pull/18 inspired by @pwithnall's blog post https://tecnocode.co.uk/2021/07/12/add-metadata-to-your-app-to-say-what-inputs-and-display-sizes-it-supports/ and ongoing work on GNOME Software which uses this data.

Today, I noticed that this metadata is not present in the appstream for Flathub on my system, even after updating it. Other apps have the same issue. Looking at apps I have installed, `org.gabmus.whatip`, `org.gnome.Extensions` and `org.gnome.World.PikaBackup` all have `<recommends>` elements, but the string `<recommends>` is not present in `/var/lib/flatpak/appstream/flathub/x86_64/active/appstream.xml`.

Could it be that Flathub is using an appstream generator which predates these tags being added to the appstream spec, and omits unrecognised tags?

**Comment by pwithnall** [comment] 2021-07-29 09:26
Certainly the requires/recommends fields are missing from [this representation of appdata](https://github.com/flathub/frontend/blob/master/src/types/Appstream.ts) in the flathub frontend code, and the fallback handling for unknown elements in [the backend code](https://github.com/flathub/backend/blob/master/app/utils.py#L10) could possibly only handle [`<control>` elements](https://www.freedesktop.org/software/appstream/docs/chap-Metadata.html#tag-requires-recommends-control) and not anything with attributes like `<display_length>`.

But it looks to me like the appstream file in the repo is separate from the appstream handling in the frontend/backend, so I don’t think I’ve found the root cause here.

**Comment by bilelmoussaoui** [comment] 2021-07-29 09:28
> Certainly the requires/recommends fields are missing from [this representation of appdata](https://github.com/flathub/frontend/blob/master/src/types/Appstream.ts) in the flathub frontend code, and the fallback handling for unknown elements in [the backend code](https://github.com/flathub/backend/blob/master/app/utils.py#L10) could possibly only handle [`<control>` elements](https://www.freedesktop.org/software/appstream/docs/chap-Metadata.html#tag-requires-recommends-control) and not anything with attributes like `<display_length>`.
> 
> But it looks to me like the appstream file in the repo is separate from the appstream handling in the frontend/backend, so I don’t think I’ve found the root cause here.

The backend/frontend just consumes the resulted appstream collection from flathub like would GNOME Software do. I think the issue is might be caused by using an older appstream.

**Comment by wjt** [comment] 2021-08-03 12:38
Quoth @barthalion on Matrix:

 > we just take what appstream-compose gives us
> so if appstream-compose skips a tag because it's been recently added to the spec but not implemented yet, I can only shrug
> switching to ximion's appstream eventually is the only way out at this point, but it doesn't have anything like "compose" yet
> the split between the desktop and appdata files probably doesn't make anything easier to app developers either, and appstream-cli can generate desktop file based on the appdata file

@ximion any suggestions/ideas here? Would `appstream-generator` need to be taught about Flatpak to be used as a replacement for `appstream-compose`?

**Comment by pwithnall** [comment] 2021-08-10 08:29
@barthalion, how easy would it be to deploy a custom version of libappstream-glib which has been patched to support `<requires>`/`<recommends>` (but isn’t available in a distro package yet)? I’m wondering if that’s the lowest-effort route to getting this working in time for GNOME 41 (which is quite important for some new functionality in gnome-software).

I haven’t yet looked at what needs doing to switch to `appstream-generator`, but it sounds harder.

**Comment by ximion** [comment] 2021-08-10 13:33
@wjt @pwithnall AppStream provides an experimental library, `libappstream-compose` for a while that allows projects to embed featureful metadata generation. AppStream Generator, since it's written in D, is not fun to embed at all (even if calling the binary executable, due to the limited platform support of LLVM/D it would restrict Flatpak) and also it is pretty specific to distribution metadata. You could likely add support for Flatpak to it as well, but I think either linking against `libappstream-compose` or calling AppStream's compose executable once that's ready is probably more convenient.

Problem with that is that I am not yet done with the compose C library and tool - at the moment I am replacing the D code bit by bit with the C library code and ultimately, `appstream-generator` will only contain the distribution-specific stuff (like cross-package icon loading, data extraction, metadata database management, etc.) while AppStream's native compose feature will give projects a framework for either basic metadata extraction or to implement something more complex on top.
I can't give any ETA for when that's done though, but since this feature is pretty important for us at Purism, there may be a good chance that I can prioritize this as Purism work...

**Comment by wjt** [comment] 2021-08-18 13:19
> @barthalion, how easy would it be to deploy a custom version of libappstream-glib which has been patched to support `<requires>`/`<recommends>` (but isn’t available in a distro package yet)?

Flathub already uses [a custom version](https://github.com/flathub/org.freedesktop.appstream-glib), at least for validating appdata. I would guess the same version is used for compose, but what do I know :)

**Comment by barthalion** [comment] 2021-08-19 10:33
Unfortunately, it's used only for validation. The compose part itself runs inside the sandbox: https://github.com/flatpak/flatpak-builder/blob/2b24480900e7871312b37c358e066c3387494c15/src/builder-manifest.c#L2304

Honestly, it probably makes more sense to run it on the host, but we'll need to patch flatpak-builder and release a new version. Then I can switch Flathub build infra to use flatpaked appstream-glib with required patches.

**Comment by wjt** [comment] 2021-08-23 15:49
Huh. I didn't realise `appstream-compose` is run at app _build_ time. Where does its output get stored per-app? Is it in the commit object? Where does each app's appdata get merged into the giant appstream file for the repo as a whole?

**Comment by barthalion** [comment] 2021-08-23 17:22
More or less, `appstream-compose` stores processed XML into `/app/share/app-info`, and this gets bundled into "collection metadata" stored in the `appstream2/$arch` ostree branch. This is what gets extracted to bare file system and served to frontends.

**Comment by ximion** [comment] 2021-08-24 01:58
So... The AppStream project (which I maintain) contains a new binary for a few hours now (currently named `appstreamcli-compose`, since the original name was taken, and installed into LIBEXEC - will likely become available as `appstreamcli compose` subcommand). This tool utilizes `libappstream-compose` and the AppStream library to compose data just like appstream-glib's compose does.
Because it uses libappstream, using it would fix this bug and bring support for every new feature that AppStream has. Internally, a lot of code for this command is shared with `appstream-generator`.
There are some caveats at the moment though:
 * `appstreamcli compose` is no drop-in replacement for `appstream-compose` because AS' compose is designed slightly differently (with processing of multiple directory trees in mind). With a different flag combination it can be instructed to do the same thing though.
 * I can not provide any stability guarantees for the library or binary at the moment. Once a release is out, I can likely guarantee a stable interface for the binary for a while, but definitely not yet for the `libappstream-compose` library.
 * The compose-code is "legacy free", so things like old directories (`/usr/share/appdata`, ...) aren't supported on purpose. Also, the compose code is *a lot* simpler than what a tool like `appstream-generator` provides, due to the limited scope of the compose binary. The intent of the `libappstream-compose` library was always to provide the basic toolbox for writing something more specific like `appstream-generator` on top. In practice this means that e.g. the icon-searching code of the compose-binary is fairly basic. I don't expect this to cause problems, since the original `appstream-compose` from appstream-glib was even more limited, but it's probably good to be aware of this.

Feedback is very welcome! In the past, Flatpak patched the AppStream libraries and added all kinds of quirks, especially modifying the validator. It would be great to avoid this, so if you have any objections or other feedback please raise it!
I'll have to do a few more things on the upcoming AppStream release before it's ready, but unless I find some dealbreaker, the compose binary will definitely be part of the AppStream 0.14.5 release (likely to be released early next month). Before that, I'll also try to compare the results of appstream's compose with appstream-glib's compose on a larger set of test data.

**Comment by ximion** [comment] 2021-08-28 23:52
If validation fails in `appstreamcli` there is something seriously wrong about the data that has to be fixed. Anything that's nice to have but doesn't make the file invalid the validator will make noise about, but won't fail validation. So I'm pretty sure Flathub will be happy with that and may actually want *stricter* checks rather than more relaxed ones...

In any case, AppStream 0.14.5 is out now, so if you want to play with `appstreamcli compose` then that's easily possible now :-)

**Comment by sophie-h** [comment] 2021-09-10 23:37
Can someone confirm that `<caption>`s missing from screenshots in Flathub metadata is related to the same issue? It's not a new feature afaik.

**Comment by dbnicholson** [comment] 2021-09-20 18:42
> Huh. I didn't realise `appstream-compose` is run at app _build_ time. Where does its output get stored per-app? Is it in the commit object? Where does each app's appdata get merged into the giant appstream file for the repo as a whole?

As @barthalion implied, it's `flatpak build-update-repo` that takes the appdata file in each app's commit and merges it into an appstream collection and puts it in the relevant `appstream2/*` ostree commit. In current flatpak that's handled by [flatpak_repo_generate_appstream](https://github.com/flatpak/flatpak/blob/master/common/flatpak-utils.c#L5749) if you want to get into the details.

**Comment by wjt** [comment] 2021-09-21 09:54
I am always confused about the flow of appstream/appdata/metainfo/app-info. So, using [Pika Backup](https://flathub.org/apps/details/org.gnome.World.PikaBackup) as an example:

- `$(flatpak info -l org.gnome.World.PikaBackup)/files/share/appdata/org.gnome.World.PikaBackup.appdata.xml` is the pristine file shipped by the application. It contains `<caption>` elements for its screenshots.
- `$(flatpak info -l org.gnome.World.PikaBackup)/files/share/app-info/xmls/org.gnome.World.PikaBackup.xml.gz` is generated when the flatpak is built. If [this fix were in the release](https://gitlab.gnome.org/World/pika-backup/-/commit/28c11eae756c6ed63eaef6761e2d9d46e8239d8d), for example, it would contain translation percentages for each language. Indeed it does not contain `<caption>` elements for its screenshots. (If we use Tuxpaint as an example, this is also the stage where the `<recommends>`/`<requires>` data goes missing.) I believe this is generated in two steps by `flatpak-builder` at app build time, both of which use the appstream tools in the app's SDK AFAICT:
  1. `appstream-compose` plus some arguments that are not important
  2. `appstream-util mirror-screenshots`
  I do not know at which step the captions go missing
- The `appstream2/*` ostree commit contains what is essentially the concatenation of those `app-info` files, generated with `flatpak build-update-repo`

**Comment by pwithnall** [comment] 2021-09-21 16:20
There are now several pending MRs open against (I think) all the relevant components for this. I think there’s some pondering to be done before I’ll know exactly how to go about tidying up and landing this all, as the release cadence of freedesktop-sdk means that we potentially can’ŧ rely on `appstreamcli` being available to `flatpak-builder` for about a year.

 * https://github.com/flatpak/flatpak/pull/4426
 * https://github.com/flatpak/flatpak-builder/pull/418
 * https://gitlab.com/freedesktop-sdk/freedesktop-sdk/-/merge_requests/6022

**Comment by darkdragon-001** [comment] 2022-10-01 10:46
Any news? Looks like only the MR in `flatpak-builder` is missing...

- [x] [Port to libappstream flatpak/flatpak#4426](https://github.com/flatpak/flatpak/pull/4426)
- [ ] [WIP: Port to libappstream flatpak/flatpak-builder#418](https://github.com/flatpak/flatpak-builder/pull/418)
- [x] https://gitlab.com/freedesktop-sdk/freedesktop-sdk/-/merge_requests/6022 -> fixed in 22.08 https://gitlab.com/freedesktop-sdk/freedesktop-sdk/-/merge_requests/6295#note_989023320

**Comment by kparal** [comment] 2022-11-01 09:47
I got linked here from a [gnome-software issue](https://gitlab.gnome.org/GNOME/gnome-software/-/issues/1956), but I haven't seen anyone mention the problem here. It seems that Flathub currently incorrectly reformats `<code>` and `<em>` tags inside appdata `<description>` and make them appear literally instead of keeping them as xml tags. The indicated solution is for Flathub to switch to libappstream. It you think that this issue is not related to libappstream, let me know, and I can file a separate ticket.

**Comment by ximion** [comment] 2022-11-01 16:20
This should indeed be resolved instantly once faltpak(-builder) uses (lib)AppStream. AFAIK the only blocker is https://github.com/flatpak/flatpak-builder/pull/418, everything else is already implemented and `appstreamcli` is also part of recent Flatpak SDKs.

**Comment by ZVNexus** [comment] 2024-01-20 16:26
Looks like this is still an issue after moving to libappstream?

**Comment by bbhtt** [comment] 2024-01-20 16:31
> Looks like this is still an issue after moving to libappstream?

It was reverted. There will be a second take some time this year.

**Comment by bbhtt** [comment] 2024-02-17 05:45
Seems to be working now, the apps is KDE Index, but GNOME calls also got rebuilt with libappstream and has the data. As more apps with the data gets rebuilt it'll pop up more often.

![image](https://github.com/flathub/flathub/assets/62639087/bfe1aff5-e934-4811-9a96-015ea6f156e2)

I think this can be closed now?

**Comment by bbhtt** [comment] 2024-02-17 05:47
> Can someone confirm that <caption>s missing from screenshots in Flathub metadata is related to the same issue? It's not a new feature afaik.

Yes, the data has captions now properly See https://github.com/flathub-infra/flatpak-builder-lint/issues/280

Website is also showing them https://flathub.org/apps/org.gnome.Calls (click the image, top left corner, @razzeee did some work for that I think)

**Closed** 2024-02-17 09:53 UTC
Labels: libappstream
