### ISSUE TITLE
Falkon is outdated

### ISSUE THREAD

**Issue by jointri** [flathub/flathub#3038] opened 2022-04-21 11:24 UTC
The package org.kde.falkon for flatpak is at 3.1.0, while upstream a stable release is at 3.2.0. 
https://www.falkon.org/
Can this please be updated?

**Comment by hfiguiere** [comment] 2022-04-21 12:02
the proper place to file the issue is with the package maintainers https://github.com/flathub/org.kde.falkon/issues

**Comment by rusty-snake** [comment] 2022-04-21 15:23
https://github.com/flathub/org.kde.falkon/issues/1
https://github.com/flathub/org.kde.falkon/issues/5

**Comment by hfiguiere** [comment] 2022-04-21 15:30
however the version on the website says 3.1.0 which mean that the appdata is likely. Again, see https://github.com/flathub/flathub/issues/3038#issuecomment-1105114640

**Comment by bilelmoussaoui** [comment] 2022-07-04 20:46
There is an issue already open on the specific application's repository, closing this one.

**Closed by bilelmoussaoui** 2022-07-04 20:46 UTC
