### ISSUE TITLE
Notifications when official builds fail

### ISSUE THREAD

**Issue by Jehan** [flathub/flathub#4677] opened 2023-11-09 11:06 UTC
I'm unsure which sub-project within the Flathub repos should handle this, so for now, I'll just make a report here.

Sometimes, builds fail unexpectedly even when they succeeded in test builds. It can be temporary build server issues, download sources unavailable, or anything else. It's fine, it happens.

The problem is that while we get notified (through Github comments) for test builds success or failures, we get absolutely no notifications for "Official" builds:

* We have to manually go to https://buildbot.flathub.org/
* Find our "Official" build (meant to be publicly published)
* Follow through to the end by looking regularly at it (it can be long, so not to forget, I usually leave the tab opened somewhere!)

This is not so good, because these are the most important builds. We had a release a few days ago, but I realized the problem only 3 days later (when someone notified us that the flatpak was not updating). And that's not the first time it happens.

Could we have notifications of success/failures for "Official" builds please?

It can just be comments in the merge request which triggered these builds (just like test builds). I.e. **once we merge** a patch to either `master` or `beta` git branches, we get similar messages "*Started official build 12345*" with a link, then when it finishes, we get a result message (success or failure with links and command line).

**Comment by bbhtt** [comment] 2023-11-09 11:54
Duplicate of https://github.com/flathub/flathub/issues/2399

**Closed** 2023-12-19 09:58 UTC
