### ISSUE TITLE
Submitting apps to flathub is too difficult

### ISSUE THREAD

**Issue by quinton-ashley** [flathub/flathub#3860] opened 2023-01-27 18:58 UTC
The process for submitting an app to flathub is way too complex. Are there any plans to simplify the process?

Ideally I'd like to submit a link to my Github repository and then have the app be available on flatpak.

Could someone please add Nostlan to Flathub for me?

https://github.com/quinton-ashley/nostlan

**Comment by quinton-ashley** [comment] 2023-01-27 19:04
I'd like to just submit a link to a Github repository and then have the app be available on flatpak.

Could someone please add Nostlan to flatpak for me?

https://github.com/quinton-ashley/nostlan

**Comment by orowith2os** [comment] 2023-01-27 22:02
Adding apps to Flathub is already very simple:

1. Make a manifest to build your app
2. Add metadata and a desktop file
3. Fork this repo, and make a PR
4. Work with reviewers to ensure the app is properly packaged
5. When merged, install from Flathub like any other, maintenance is fairly simple

Just adding a link to your git repo will not be sufficient, as there needs to be effort put into it and maintenance done.

**Comment by quinton-ashley** [comment] 2023-01-28 12:40
That's really not a simple process at all though, just trying to give you an average user's perspective. Ideally there should be a tool that can help users automatically upload an appimage to flathub. Uploading to Apple's App Store or the Windows Store is way easier.

**Comment by orowith2os** [comment] 2023-01-28 14:56
An average users perspective doesn't matter here because maintaining a flatpak isn't for the average user, it's left to package maintainers that know how it works. 

Flathub is also not Apple's or Microsoft's app stores, nor does it function the same. Comparing the two can be like comparing apples to oranges.

**Comment by quinton-ashley** [comment] 2023-01-28 15:03
@orowith2os Okay let's compare it to `npm` then. Flathub is horrible by comparison.

**Comment by quinton-ashley** [comment] 2023-01-28 15:25
me:  "It's hard to learn how to submit an app to FlatHub and the process is overly complex compared to other tools I've used."

you 🤡 : "Your perspective doesn't matter because maintaining a flatpak is up to people that know how to do it."

**Comment by TheEvilSkeleton** [comment] 2023-01-28 16:29
To be frank, you are expecting Flathub to be something else, without really taking Linux's issues into consideration, which is extremely unfair. One could make the same argument that npm is difficult to use, just because they are unfamiliar with it.

That being said, Flathub's process is "difficult" because it does everything it can to comply with freedesktop.org standards. An [appstream](https://www.freedesktop.org/software/appstream/docs/) file is required so other software centers, like GNOME Software and KDE Discover, can read metadata from of the app and display the information correctly.

A desktop entry is required so application launchers, application menus, and the likes, can find and launch the application, with appropriate information like icons, name, etc.

Additionally, Flathub pushes offline building and [reproducible builds](https://en.wikipedia.org/wiki/Reproducible_builds) unconditionally, for security and consistency purposes. I do admit that those make the submitting process a lot more difficult, but they're needed to address some concerns with the chain of trust model.

You could discuss with the Flathub maintainers to automatically publish using internal infra, like GitHub Actions. For example, OBS Studio uses GitHub Actions to publish to Flathub as well: https://github.com/obsproject/obs-studio/pull/5569. I don't know how it works, so you'll need to ask them, though.

---

> me: "It's hard to learn how to submit an app to FlatHub and the process is unnecessarily complex compared to other tools I've used."
> 
> you :clown_face: : "Your perspective doesn't matter because maintaining a flatpak is for people that know how it works."

See, with this attitude, no one would want to help. I've reconsidered my decision after reading this.

**Comment by Kellegram** [comment] 2023-01-28 16:35
> me: "It's hard to learn how to submit an app to FlatHub and the process is unnecessarily complex compared to other tools I've used."
> 
> you 🤡 : "Your perspective doesn't matter because maintaining a flatpak is for people that know how it works."

I don't think you have any idea what flatpak actually does that most package managers don't. The consumer user experience for npm is horrible, one of the worst out there, with massive issues with versions, malware, compatibility problems, etc. Flatpak avoids all of that. With npm ahving an environment manager is basically a must just to have a slightly passable experience, whereas with flatpak, maintainers do work on their side so that you have a good experience from the get go as a consumer. Flatpak's publishing process isn't simple because its inner workings aren't simple, but come with benefits that you completely failed to acknowledge. Flatpak can be messy under the hood, which is expected from a less adopted system that's also 5 years younger than npm, but that again does not acknowledge the fact that flatpak is just more complex in general.

**Comment by quinton-ashley** [comment] 2023-01-28 17:03
npm is easy to use for users and developers. I've never had issues with it but cope harder.

While the flatpak user experience is great, you all can't be serious thinking that an app submission process that requires forking a repository, making another branch, learning a non-standard manifest file format, submitting a pull request, etc. is something that the average developer is going to want to go through. The submissions tutorial is like 10 pages long, that's so embarrassing. None of you ever thought "Wouldn't it be better to make a tool that automates this process or a website with a submission form instead?"

**Comment by orowith2os** [comment] 2023-01-28 17:05
Here's my own little two cents, on top of what Skel and Kell said:

Im going to explain why you're wrong: why complaining that the application submission process is too difficult is the perfect example of not understanding how Linux packaging works and flatpak, and why your application will need work to be done on it to work properly in Flatpak.

You don't seem to understand how package management on Linux (or Flatpak/Flathub, for that matter) works. Package build recipes and workflows to build it and all related things are traditionally separate from the main application on Linux, with exceptions such as OBS where builds are done upstream. Additionally, submitting an application to Flathub isn't ever going to be as simple as posting a GitHub link. You will need to put in effort for your application to work properly, and will need to discuss your manifest with Flathub reviewers before it can be added, such as fine tuning the permissions so it doesn't have unnecessary system access.

Flatpak and Flathub are also not other package management systems. They are entirely separate projects, meant to address different concerns. Applying ideals from one package management system to flatpak will not turn out well.

Your application seems to work similarly to Lutris, which has encountered some issues with emulators and whatnot. Flatpak doesn't allow flatpaks to launch other flatpaks without sandbox escapes like flatpak-spawn, and that is very dangerous. Lutris ended up bundling ALL its emulators so that it worked OOTB, and this caused the builds to take hours. Applications that require that functionality aren't very fit for Flatpak packaging unless they explicitly account for it.

**Comment by Kellegram** [comment] 2023-01-28 17:06
Lol, loving those 12yo child vibes, self-reacting to their own post to make it seem like someone agrees, spamming clown emoji, acting like developers are intentionally making things harder. Average child. I'm out.

**Comment by quinton-ashley** [comment] 2023-01-28 17:06
Why should I care how package management on Linux is done? I'm an app developer. Shouldn't that be your job as the developer of a package manager? lol

**Comment by quinton-ashley** [comment] 2023-01-28 17:09
>>> Your application seems to work similarly to Lutris, which has encountered some issues with emulators and whatnot. Flatpak doesn't allow flatpaks to launch other flatpaks without sandbox escapes like flatpak-spawn

Got it so flatpak is unusable for my use case and actually sucks way harder than I thought.

**Comment by rmnscnce** [comment] 2023-01-28 17:10
> In reply to @quinton-ashley at [comment-1407440857](https://github.com/flathub/flathub/issues/3860#issuecomment-1407440857)

While staging out the whole manifest format may not ever happen, I'd agree that the developer experience could see some love. I also see that there are things that could be streamlined to improve the experience and make it as friction-less as possible while maintaining reproducibility and the level of scrutiny (which honestly is not that bad for Linux standards) that applies to the apps hosted on Flathub.

**Comment by orowith2os** [comment] 2023-01-28 17:11
@quinton-ashley I'm not going to package your app if the upstream (you) is this toxic. You're coming off as a giant ass, and you were the one in the first place to complain that the process was too complicated. If you complain about it, then you shoukd obviously be the one to learn how packages are done on Linux ;)

And no, it actually doesn't "suck as hard as you thought", as you can still achieve the desired end result. It will just take some effort, which you don't seem to want to put in at all, judging from your attitude.

**Comment by quinton-ashley** [comment] 2023-01-28 17:16
@orowith2os Your response was toxic, telling me my perspective didn't matter. I gave me feedback and immediately you just respond saying "actually it is simple". Not being able to accept criticism is the definition of toxic.

**Comment by TheEvilSkeleton** [comment] 2023-01-28 17:17
This is obviously going nowhere. No one denies that Flathub and Flatpak need improvements. We all want the packaging process to be better, but no one seems to step up and explain what needs to be improved. @barthalion can you lock this issue?

**Comment by quinton-ashley** [comment] 2023-01-28 17:17
Literally the first response was denial

**Comment by barthalion** [comment] 2023-01-28 17:21
There is no doubt the submission process is less than ideal, and I generally don't agree with arguments saying that "Flatpak is different and other tools are also bad". We should do better, but we've got sparse resources (and my usage of plural form is really an overstatement), and developer experience didn't get any attention since Flathub exists.

That being said, there's nothing actionable about this issue right now. I can only encourage you to poke around [existing submissions](https://github.com/search?q=org%3Aflathub+AppImage+language%3AYAML&type=code&l=YAML) (like [OSU](https://github.com/flathub/sh.ppy.osu/blob/4251f5b5f70e71f3f6c66a21301fa135927d2fde/sh.ppy.osu.yaml#L45)) to see how AppImages can be re-used on Flathub. Nostlan might be difficult to get right as it seems to launch external emulators, and it has already been challenging for RetroDeck.

**Closed by barthalion** 2023-01-28 17:21 UTC

**Comment by quinton-ashley** [comment] 2023-01-28 17:26
@barthalion @rmnscnce  Thank you for at least acknowledging the problem. My intent with opening this issue was not to start a whole argument.

**Comment by mfat** [comment] 2024-12-19 03:17
Well as a novice developer struggling with my first submission i feel qulified to comment here :)

A package submission "wizard" would be absolutely worth it—developer experience matters. Not all devs are Git experts, and lowering the barrier to entry can make a big difference.

The wizard doesn’t need to be fancy—even a simple Bash script would work. By making submissions easier, you’ll attract more developers and help the platform grow and evolve in the long run.

**Comment by bbhtt** [comment] 2024-12-19 03:25
we don't need more submissions, there are enough as is.
