### ISSUE TITLE
Ability to set a different app-id for a beta release

### ISSUE THREAD

**Issue by Jehan** [flathub/flathub#1915] opened 2020-11-02 12:13 UTC
Several people are complaining that they cannot easily run both the stable and beta version of the org.gimp.GIMP package. We tell them they can specifically run one or the other by command line (ex: `flatpak run org.gimp.GIMP//stable`), but for desktop launch, they have to change the main version each time with `flatpak make-current` (or they can manually create shortcuts or separate desktop files).

We were proposed to just use a [different app-id for the beta](https://github.com/flatpak/flatpak/issues/1109#issuecomment-337228635). I am not fond of this idea, but was willing to try this as a workaround (waiting for a better solution). So I tried this (as well as made sure all the `rename-*` were set), but the package creation [fails at "Check for AppStream xml" step](https://github.com/flathub/org.gimp.GIMP/issues/91#issuecomment-717863707):

```
stat: cannot stat 'builddir/*/share/app-info/xmls/org.gimp.GIMP.xml.gz': No such file or directory
```

More information on the associated report: https://github.com/flathub/org.gimp.GIMP/issues/91#issuecomment-717863707

I am not sure if I am doing something wrong, or if there is a bug on Flathub side. It looks like this step is using maybe the repository name instead of the app-id? So when the app-id is different, the package creation fails. If so, I understand this limitation on the stable branch, but it should likely not be enforced on the beta branch (maybe only a check like the app-id for a beta branch has to be prefixed by the stable app-id, so `org.gimp.GIMP*` in our case).

Yet if any other application is already using the same trick, I would guess the problem is in my manifest, but if so, could you help please? Thanks! 🙂

**Comment by bilelmoussaoui** [comment] 2020-11-02 12:43
Currently, an application can't have multiple ids. They are technically not the same application anymore.

**Comment by Jehan** [comment] 2020-11-02 13:01
@bilelmoussaoui So this trick is not supported on Flathub? This is @alexlarsson who proposed this trick (he did on a bug report and again recently on Twitter). So I did assume there was maybe a hidden feature.

**Comment by barthalion** [comment] 2020-11-02 15:20
Different ID implies being different application. This is how VS Code is handled:

https://github.com/flathub/com.visualstudio.code.insiders
https://github.com/flathub/com.visualstudio.code

The `insiders` variant is available only in flathub-beta.

**Comment by bbhtt** [comment] 2024-07-10 15:50
Dupe of https://github.com/flathub/flathub/issues/1138

**Closed by bbhtt** 2024-07-10 15:50 UTC
Labels: infrastructure
