### ISSUE TITLE
Unable to use create-usb command, no collection ID set

### ISSUE THREAD

**Issue by cmurf** [flathub/flathub#1048] opened 2019-06-24 02:52 UTC
[chris@fmac ~]$ flatpak create-usb /run/media/chris/03b9c14b-f121-43b2-814c-a46b3a263b32/flatpaks/ com.slack.Slack
error: Remote ‘flathub’ does not have a collection ID set, which is required for P2P distribution of ‘app/com.slack.Slack/x86_64/stable’.

Always reproducible.

**Comment by rivetchip** [comment] 2019-07-06 20:41
Got the same error, it's triggered here : [flatpak/flatpak/blob/master/app/flatpak-builtins-create-usb.c#L234](https://github.com/flatpak/flatpak/blob/master/app/flatpak-builtins-create-usb.c#L234)

From what I understand you need to have a "collection-id" key in repo config here : /var/lib/flatpak/repo/config

example : 
```
[remote "flathub"]
...
collection-id=something
```

But I cant figure it out what the collection ID should be :disappointed: 

[This issue](https://github.com/flatpak/flatpak/issues/2020) mention "org.flathub.Stable" but it's not working either

**Comment by Zzombiee2361** [comment] 2019-11-16 11:53
I've managed to get it working by this command
`flatpak remote-modify --collection-id=org.flathub.Stable flathub`

But when i tried to run create-usb command, I got this error:
`error: Importing 250415c36700e8c31b437b342c25ba6c3a5265d11cc4cd783dbbea15b991d8fd.commit: renameat: Function not implemented`

**Comment by barthalion** [comment] 2020-01-20 21:53
Duplicate of https://github.com/flathub/flathub/issues/676.

**Closed by barthalion** 2020-01-20 21:53 UTC
