### ISSUE TITLE
Atom installation fails as server returns 503 for freedesktop SDK

### ISSUE THREAD

**Issue by rugk** [flathub/flathub#935] opened 2019-04-01 19:40 UTC
```sh
flatpak --system install --from https://flathub.org/repo/appstream/io.atom.Atom.flatpakref
Required runtime for io.atom.Atom/x86_64/stable (runtime/org.freedesktop.Sdk/x86_64/18.08) found in remote flathub-1
Do you want to install it? [Y/n]: y

io.atom.Atom permissions:
    ipc       network       pulseaudio            ssh-auth
    x11       devices       file access [1]       dbus access [2]

    [1] host, xdg-config/kdeglobals:ro
    [2] com.canonical.AppMenu.Registrar, com.canonical.AppMenu.Registrar.*,
        org.freedesktop.Flatpak, org.freedesktop.Notifications,
        org.freedesktop.secrets, org.gtk.vfs, org.gtk.vfs.*


        ID                                         Arch   Branch Op Remote       Download
 1. [?] org.freedesktop.Sdk                        x86_64 18.08  i  flathub-1      286.3 MB / 596.1 MB
 2. [ ] org.freedesktop.Sdk.Locale                 x86_64 18.08  i  flathub-1    < 319.3 MB (partial)
 3. [ ] org.freedesktop.Platform.Icontheme.Adwaita x86_64 1.0    u  gnome         < 12.6 MB
 4. [ ] org.freedesktop.Platform.html5-codecs      x86_64 18.08  i  flathub-1      < 4.9 MB
 5. [ ] io.atom.Atom                               x86_64 stable i  atom1-origin < 141.5 MB

Error: While pulling runtime/org.freedesktop.Sdk/x86_64/18.08 from remote flathub-1: Server returned HTTP 503
error: Failed to install org.freedesktop.Sdk: While pulling runtime/org.freedesktop.Sdk/x86_64/18.08 from remote flathub-1: Server returned HTTP 503
```

---

also reported as https://github.com/flathub/io.atom.Atom/issues/45

**Comment by TingPing** [comment] 2019-04-01 21:13
These just happen sometimes:

Duplicate of #845

**Closed by TingPing** 2019-04-01 21:13 UTC
