### ISSUE TITLE
Add extension support to the Flathub website

### ISSUE THREAD

**Issue by Jehan** [flathub/flathub#1612] opened 2020-06-23 09:37 UTC
GIMP now has 2 extension points. A "Manual" one (tied with an official flatpak and auto-installed together) and a "Plugin" one. 5 third-party plug-ins have already been created and now published on Flathub.

Unfortunately these are not visible/searchable on the website (only way I can see to list them all is through command line `flatpak search org.gimp.GIMP.Plugin`). I would propose that on the `flathub.org/apps/details/<appid>` page are listed all available extensions for a given `appid` and the command line to install them (or the link to extension page as generated from appdata so that one can look up description before installing).

Note that this is even interesting for the Manual extension, even in auto-install because we recommend people to force reinstall it (with `flatpak install --reinstall flathub org.gimp.GIMP.Manual`) if they want all languages. Indeed the manuals are not localized in all languages and GIMP allows people to select a specific language in Preferences. Forcing reinstall actually installs all localizations (unlike the default install).

**Comment by bilelmoussaoui** [comment] 2020-06-23 09:43
Duplicate of https://github.com/flathub/linux-store-frontend/issues/47

**Closed by bilelmoussaoui** 2020-06-23 09:43 UTC
