### ISSUE TITLE
Support exporting higher resolution app icons for HiDPI

### ISSUE THREAD

**Issue by vchernin** [flathub/flathub#2495] opened 2021-09-07 05:55 UTC
Installing and using Flatpaks on a HiDPI (4k, 27") display I find app icons are often blurry, despite knowing the upstream files are much sharper. I opened an issue [against GNOME Software](https://gitlab.gnome.org/GNOME/gnome-software/-/issues/1426), but I was directed here as this may be a limitation of Flathub's current build process and not GNOME Software.

Could Flathub support exporting higher resolution app icons, eg 256x256 or even 512x512? Is there any way an SVG file could be used directly or is there a Flatpak/Flathub limitation with SVGs somewhere?

**Comment by barthalion** [comment] 2021-09-07 13:49
This is a combination of Flatpak and appstream-glib/appstream-cli (note these are separate projects). Flathub on its own just uses these tool so we are bound to what they provide.

**Comment by vchernin** [comment] 2021-09-07 18:36
I couldn't really find relevant issues about this topic in those projects, so I guess I should open issues in all 3?

**Comment by pwithnall** [comment] 2021-09-08 10:31
> I couldn't really find relevant issues about this topic in those projects, so I guess I should open issues in all 3?

Hang on, I’ll dig into the issue a bit more later today and try to work out exactly what changes need to be made. Might not need 3 new issues. I’ll report back here

**Comment by pwithnall** [comment] 2021-09-08 14:03
Having dug into a bit, I think the root cause of the issue is that appstream-glib (which is used to compose the metainfo files from multiple projects into the appstream shipped by flathub) [doesn’t support more than 64x64 and 128x128 both at scale=1](https://github.com/hughsie/appstream-glib/blob/master/client/as-compose.c#L87-L160). It needs to support them both at scale=2.

appstream-glib’s compose tool is hard-coded to be used by [flathub](https://github.com/flathub/org.freedesktop.appstream-glib) and [flatpak](https://github.com/flatpak/flatpak-builder/blob/2b24480900e7871312b37c358e066c3387494c15/src/builder-manifest.c#L2304), as explained by @barthalion [here](https://github.com/flathub/flathub/issues/2439#issuecomment-901802541). Of those, the use of appstream-glib in flatpak is more relevant here, as that’s what does appstream composition. Its use in flathub is just for validation.

Given the [new availability of `appstreamcli compose`](https://github.com/flathub/flathub/issues/2439#issuecomment-904259156), perhaps it is now feasible to fix this (and https://github.com/flathub/flathub/issues/2439) by switching to `appstreamcli compose` rather than continuing to use appstream-glib. appstream-glib is deprecated and largely unmaintained.

The alternative is to add support for scale=2 to appstream-glib and wait for those changes to filter through to the flathub infrastructure. That would (aiui) mean waiting for an updated runtime build with the fixes.

I guess the approach to use is up to @barthalion.

---

One other thing worth noting is that appstream has supported a `scale` attribute on `<icon/>` for a while, but it wasn’t [documented in the specification](https://www.freedesktop.org/software/appstream/docs/chap-Metadata.html#tag-icon). I’ve tried to fix that here: https://github.com/ximion/appstream/pull/353

**Comment by bbhtt** [comment] 2024-03-23 14:41
128@2 are exported now with the switch to libappstream and updateing appstream to 1.0.2. Eg. https://dl.flathub.org/media/app/drey/Biblioteca/e46ca81864ff6e8946c5dfc823243cb0/icons/128x128@2/app.drey.Biblioteca.png

I don't think there are plans to have higher than 128@2 icons. Closing as solved.

**Closed by bbhtt** 2024-03-23 14:41 UTC
Labels: libappstream

**Comment by razzeee** [comment] 2024-03-23 15:53
For reference, this will need a scalable svg icon to be included with an app, for these to get created.
