### ISSUE TITLE
Flatpak'd Steam doesn't set udev rules for Steam Controller hardware

### ISSUE THREAD

**Issue by kostich** [flathub/flathub#278] opened 2018-02-25 08:47 UTC
Current Steam flatpak doesn't set udev rules on Fedora Atomic Workstation 27 (rebased to Rawhide).

```
flatpak info com.valvesoftware.Steam 
Ref: app/com.valvesoftware.Steam/x86_64/stable
ID: com.valvesoftware.Steam
Arch: x86_64
Branch: stable
Origin: flathub
Date: 2018-02-12 20:41:49 +0000
Subject: Grant read access to xdg-music (581af74e)
Commit: effe21b05e42c4a225dde8feffc14280e8c4045fa841ea745ed17bcc830560ca
Parent: 4819a16e6494c41dfd2901432a91a6c73177bc3f6c708a9059e90325ae0ab0be
Location: /var/lib/flatpak/app/com.valvesoftware.Steam/x86_64/stable/effe21b05e42c4a225dde8feffc14280e8c4045fa841ea745ed17bcc830560ca
Installed size: 6,3 MB
Runtime: org.freedesktop.Platform/x86_64/1.6
```

To be able to use the Steam Controller with the Steam Flatpak, we need to extract the rules from an existing RPM, copy them to `/etc/udev/rules.d/` and exec the `udevadm control --reload-rules && udevadm trigger` command (or reboot the host).

Is it possible to have this done automatically when the Flatpak is installed, to improve the UX?

**Comment by TingPing** [comment] 2018-02-25 13:52
This isn't possible without really nasty hacks.

Duplicate of https://github.com/flathub/com.valvesoftware.Steam/issues/8

**Closed by TingPing** 2018-02-25 13:52 UTC
