### ISSUE TITLE
Peer failed to perform TLS handshake

### ISSUE THREAD

**Issue by dsboger** [flathub/flathub#417] opened 2018-06-02 01:43 UTC
I'm having this error whenever I `flatpak update/install` from flathub (so far it never happened with gnome-nightly or gnome-apps-nightly, my other two remotes):

```
Installing: org.kde.Platform/x86_64/5.11 from flathub
[##                  ] Downloading: 4,6 MB/161,1 MB (1,5 MB/s)
Error: Failed to install org.kde.Platform/x86_64/5.11: While pulling runtime/org.kde.Platform/x86_64/5.11 from remote flathub: Peer failed to perform TLS handshake
```

Fortunately flatpak saves partial download progress, so I can call it multiple times and it eventually finishes.

I'm not sure where the issue is, so I'm reporting here in hopes of getting some pointers.

Thanks!

**Comment by prashantdream** [comment] 2018-06-12 11:40
![screenshot from 2018-06-12 17-09-02](https://user-images.githubusercontent.com/16290075/41288292-7069491c-6e63-11e8-88c5-4f583e8c5bbc.png)
I have to save problem when installing through Endless App Center

**Comment by dsboger** [comment] 2018-06-28 21:41
I don't know if anything has been done about this issue, but nothing changed to me. Please, let me know if I can do anything to help.

**Comment by marcelpaulo** [comment] 2018-07-31 11:27
It has just happened to me:

```
paulo:~$ flatpak update -y
Looking for updates...
flatpak update: Error updating remote metadata for 'flathub': Peer failed to perform TLS handshake
error: Unable to load summary from remote flathub: Peer failed to perform TLS handshake
```

I'm running flatpak from _ppa:alexlarsson/flatpak_:

```
paulo:~$ flatpak --version
Flatpak 0.99.3
```

on Xubuntu 18.04.

But it seemed to be a temporary issue with the flathub server itself, since when I tried again some moments later, to capture debugging output, it succeeded:

```
paulo:~/tmp$ flatpak update -y -v &> >(tee flatpak.log)
F: Opening user flatpak installation at path /home/paulo/.local/share/flatpak
F: Opening system flatpak installation at path /var/lib/flatpak
F: No installations directory in /etc/flatpak/installations.d. Skipping
Looking for updates...
F: Fetching summary file for remote ‘flathub’
F: Transaction: update flathub:app/org.freedesktop.Bustle/x86_64/stable[$old]
F: Transaction: update flathub:app/org.gimp.GIMP/x86_64/stable[$old]
F: Transaction: update flathub:runtime/org.freedesktop.Platform.Locale/x86_64/1.6[$old]
F: Transaction: update flathub:runtime/org.freedesktop.Platform.VAAPI.Intel/x86_64/1.6[$old]
F: Transaction: update flathub:runtime/org.freedesktop.Platform.ffmpeg/x86_64/1.6[$old]
F: Transaction: update flathub:runtime/org.freedesktop.Platform/x86_64/1.6[$old]
F: Transaction: update flathub:runtime/org.gnome.Platform.Locale/x86_64/3.26[$old]
F: Transaction: update flathub:runtime/org.gnome.Platform.Locale/x86_64/3.28[$old]
F: Transaction: update flathub:runtime/org.gnome.Platform/x86_64/3.26[$old]
F: Transaction: update flathub:runtime/org.gnome.Platform/x86_64/3.28[$old]
F: Transaction: update flathub:runtime/org.gtk.Gtk3theme.Greybird/x86_64/3.22[$old]
F: Updating remote metadata for flathub
F: marking op update:runtime/org.gtk.Gtk3theme.Greybird/x86_64/3.22 resolved to c2704647ab514954185cb4c8d3a14893383eda695a4d1ef6c9275657b9b2b26b
F: marking op update:runtime/org.gnome.Platform/x86_64/3.28 resolved to cc7c2dd516160674998803e6ed6838091d628a3d25ff7465485ddecfb9f4363f
F: marking op update:runtime/org.gnome.Platform/x86_64/3.26 resolved to ce4fc76f0f4eddc925b3c0a857aed453c1d661a64d5eb5367947a0517c1ccc55
F: marking op update:runtime/org.gnome.Platform.Locale/x86_64/3.28 resolved to 1d96abcdc97bf21f68853f8c3d238fafa65ef71040b6cc4799fbcd70c6c18f22
F: marking op update:runtime/org.gnome.Platform.Locale/x86_64/3.26 resolved to 9d202b1b339c74311ee1f77aa8c3aaee52c02ed4f95fd4f9221043d7cefe9141
F: marking op update:runtime/org.freedesktop.Platform/x86_64/1.6 resolved to 3b442ccf3e8eb746db8cca8779f37a8cf5038ff835f063ff8d53cdb330b94e4c
F: marking op update:runtime/org.freedesktop.Platform.ffmpeg/x86_64/1.6 resolved to d757f762489e444551d17223590635d4f4014a36b6fecd73323bf3f95f1aa490
F: marking op update:runtime/org.freedesktop.Platform.VAAPI.Intel/x86_64/1.6 resolved to 82006efc71d3c9e122ee6845147920ef6fe4054d4978f8686120afc85e89f2b0
F: marking op update:runtime/org.freedesktop.Platform.Locale/x86_64/1.6 resolved to 4e63310c1c0738e585fe1b524c3c92e9e7b93e85bd388564a1c9b9253fe7765d
F: marking op update:app/org.gimp.GIMP/x86_64/stable resolved to b3820ea6299f51baa4807aa8488ef57488aca8f6f819637e950477fec17d1285
F: marking op update:app/org.freedesktop.Bustle/x86_64/stable resolved to 7a39c61485a030525978dadd7759f99485dd491bca4ad4b2caf63f4484584c5e
F: Transaction: install/update flathub:runtime/org.freedesktop.Platform.VAAPI.Intel/x86_64/1.6[*]
F: Transaction: install/update flathub:runtime/org.freedesktop.Platform.ffmpeg/x86_64/1.6[*]
F: Transaction: install/update flathub:runtime/org.gtk.Gtk3theme.Greybird/x86_64/3.22[*]
F: Transaction: install/update flathub:runtime/org.gnome.Platform.Locale/x86_64/3.28[/en]
F: Transaction: install/update flathub:runtime/org.freedesktop.Platform.VAAPI.Intel/x86_64/1.6[*]
F: Transaction: install/update flathub:runtime/org.freedesktop.Platform.ffmpeg/x86_64/1.6[*]
F: Transaction: install/update flathub:runtime/org.gtk.Gtk3theme.Greybird/x86_64/3.22[*]
F: Transaction: install/update flathub:runtime/org.gnome.Platform.Locale/x86_64/3.26[/en]
F: Transaction: install/update flathub:runtime/org.freedesktop.Platform.VAAPI.Intel/x86_64/1.6[*]
F: Transaction: install/update flathub:runtime/org.freedesktop.Platform.ffmpeg/x86_64/1.6[*]
F: Transaction: install/update flathub:runtime/org.gtk.Gtk3theme.Greybird/x86_64/3.22[*]
F: Transaction: install/update flathub:runtime/org.freedesktop.Platform.Locale/x86_64/1.6[/en]
F: flathub:x86_64 appstream age 156 is less than ttl 86400
```

@dsboger, if you don't experience the problem anymore, you could consider closing this issue.

**Comment by riley-martine** [comment] 2018-08-19 11:08
Getting the same error, also resolves itself after a few tries:
```
✘ riley@librem  ~/dev/analyze/data   master ●  flatpak install flathub org.nextcloud.Nextc│
loud                                                                                           │
Installing in system:                                                                          │
org.kde.Platform.Locale/x86_64/5.9           flathub 419358ad4f0a                              │
org.nextcloud.Nextcloud/x86_64/stable        flathub c64a9f921a09                              │
  permissions: ipc, network, x11                                                               │
  file access: host, xdg-run/Nextcloud:create                                                  │
  dbus access: org.freedesktop.Notifications, org.freedesktop.secrets, org.kde.StatusNotifierWa│
tcher                                                                                          │
org.nextcloud.Nextcloud.Locale/x86_64/stable flathub 25369c8c99d4                              │
Is this ok [y/n]: y                                                                            │
Installing: org.kde.Platform.Locale/x86_64/5.9 from flathub                                    │
error: Failed to install org.kde.Platform.Locale/x86_64/5.9: Peer failed to perform TLS handsha│
ke                                                                                             │
 ✘ riley@librem  ~/dev/analyze/data   master ●  flatpak install flathub org.nextcloud.Nextc│
loud                                                                                           │
error: Unable to load summary from remote flathub: Peer failed to perform TLS handshake
 ```


Possibly extenuating circumstances: in China, connecting over VPN (Cisco Anyconnect for school), running PureOS on Librem 15.

**Comment by ankushdas9** [comment] 2018-08-24 14:13
Same here. Anyone with a fix?

**Comment by riley-martine** [comment] 2018-08-28 02:03
@ankushdas9 my fix was retrying it a few times

**Comment by joergister** [comment] 2018-08-28 13:11
My fix was a stable and fast connection to the internet. 

Before I had a very slow connection and I was running updates on my fedora system at the same time. Flatpak somhow didn't get enough bandwidth it seems.

**Comment by nedrichards** [comment] 2018-09-14 21:16
It's certainly an issue, but I agree it's behaviour that flatpak itself should do more to mitigate.

**Closed by nedrichards** 2018-09-14 21:16 UTC

**Comment by Ruedii** [comment] 2018-10-05 07:05
I'm running into this issue now.

I think the issue is somehow with the server configuration on Flathub, although it is aggrevated by the way FlatPak handles TLS.

**Comment by tidux** [comment] 2018-11-11 21:01
I was able to diagnose this as a system clock issue on my system.  My clock was ~30s ahead of the Flathub server which caused TLS to fail.  Running `ntpdate pool.ntp.org && hwclock --systohc` and re-running the flatpak command resolved the issue.

**Comment by Ruedii** [comment] 2018-12-05 08:35
Tidux's fix did not fix it for all affected.

I did track down the issue.  OSTree is opening too many connections at once, and not properly reading connections that fail to open as a sign of network congestion.

**Comment by ZapDos7** [comment] 2019-02-23 14:14
The issue remains for me as well. I tried installing what I needed through Ubuntu Software, since I could, but neither the clocking solution nor retrying many times worked for me, and changing ISP is, currently, out of the question.

**Comment by caioraposo** [comment] 2019-03-28 21:35
Same error here, no matter how many times I try.

**Comment by frdsofficial** [comment] 2019-04-14 18:46
> I was able to diagnose this as a system clock issue on my system. My clock was ~30s ahead of the Flathub server which caused TLS to fail. Running `ntpdate pool.ntp.org && hwclock --systohc` and re-running the flatpak command resolved the issue.

That worked to me thanks!

**Comment by AlexTrapp** [comment] 2019-04-24 19:59
Just kept trying, 4th time it went all the way through.  Any hesitation in the connection will cause this.

**Comment by drom98** [comment] 2019-07-28 12:52
Still have the same error.

**Comment by Reno-Sifana** [comment] 2023-02-01 13:08
> I've not seen this error anymore since I've switched to a different ISP. Now I think the issue is more likely to be a "lack of lenience" on the flatpak downloader than on flathub.

Maybe yes. When i running speedtest-cli in terminal showing error message errno 104. It Seems my Internet Connection not reliable
