### ISSUE TITLE
'Server returned HTTP 503' from time to time.

### ISSUE THREAD

**Issue by mkrajnak** [flathub/flathub#845] opened 2019-02-06 11:16 UTC
I noticed that when I am using flathub frequently, e.g. installing several apps in a row i've have been getting this error from time to time with some apps (not the same app), in both command line and gnome-software.

![index](https://user-images.githubusercontent.com/10319675/52337326-a3a2bd80-2a07-11e9-9438-18015609e4de.jpg)

```
error: Failed to install org.jamovi.jamovi/x86_64/stable: While pulling app/org.jamovi.jamovi/x86_64/stable from remote flathub: Server returned HTTP 503\n'
```
This might be rather a question than issue, so is this a security precaution from the server to prevent an overload from certain clients or am I hitting some possible issue with service stability ?

**Comment by mcatanzaro** [comment] 2019-03-14 16:05
Seems to be impossible to install `org.gnome.Sdk.Debug//3.30` right now. I've tried three times:

```
 flatpak install --user org.gnome.Sdk//3.30 org.gnome.Sdk.Debug//3.30
Looking for matches…
Found similar ref(s) for ‘org.gnome.Sdk//3.30’ in remote ‘flathub’ (user).
Use this remote? [Y/n]: y


        ID                     Arch     Branch   Remote    Download
 1. [✗] org.gnome.Sdk.Debug    x86_64   3.30     flathub     196.1 MB / 6.2 GB
 2. [ ] org.gnome.Sdk          x86_64   3.30     flathub     < 1.8 GB
 3. [ ] org.gnome.Sdk.Locale   x86_64   3.30     flathub   < 226.3 MB (partial)

Error: While pulling runtime/org.gnome.Sdk.Debug/x86_64/3.30 from remote flathub: Server returned HTTP 503
error: Failed to install org.gnome.Sdk.Debug: While pulling runtime/org.gnome.Sdk.Debug/x86_64/3.30 from remote flathub: Server returned HTTP 503
```

**Comment by rugk** [comment] 2019-04-01 21:18
Note that it really only happens for this one flatpak then for some time. So it really looks like a DDOS protection… (but you do have to expect many and large file downloads, that's just how it is)

**Comment by mkrajnak** [comment] 2019-04-02 14:26
> Note that it really only happens for this one flatpak then for some time. So it really looks like a DDOS protection… (but you do have to expect many and large file downloads, that's just how it is)

Well this is happening for me for multiple flatpaks from flathub not only one :(

**Comment by rugk** [comment] 2019-04-02 17:13
Yes, but not _all_ of them, so… that was my point.

**Comment by pouar** [comment] 2019-12-31 03:35
Happens every time I try to install org.freedesktop.Sdk.Extension.texlive. Wouldn't be so bad if flatpak didn't try to redownload the whole thing from scratch instead of resuming where it left off.

**Comment by pouar** [comment] 2019-12-31 03:52
There wouldn't happen to be a way to get flatpak to resume from where it left off that I don't know about would there?

**Comment by NighttimeDriver50000** [comment] 2020-01-17 14:13
I too am having this issue. How long do you usually have to wait?

**Comment by mkrajnak** [comment] 2020-01-17 14:18
Not sure but since more and people are having trouble with this I suspect that flathub has probably some problems dealing with heavy traffic.

**Comment by barthalion** [comment] 2020-01-17 17:24
I'm trying to free some disk space as publishing updates is blocked for 20-30h now and that kills the drive. I applied some `ionice` but can't promise how much it's going to help. Going to stop the process in 2-3 hours.

**Comment by barthalion** [comment] 2020-01-17 19:26
OK, we're back. I'll close it for now; next week we're migrating to new server and that should help with infrastructure-related 503s.

**Comment by barthalion** [comment] 2020-01-20 13:56
Migration was finished so hopefully random 503 will be gone.

**Comment by junjieyuan** [comment] 2020-02-05 14:13
This issue may still not be resolved. Downloading large files is extremely slow and still returns 503. 

I downloaded texstudio twice, the download speed is very low (<45 KB/s), and I always get 503 errors.

[texstudio issue](https://github.com/flathub/org.texstudio.TeXstudio/issues/39)

```text
[junjie@xps ~]$ flatpak install flathub org.texstudio.TeXstudio
Looking for matches…
Required runtime for org.texstudio.TeXstudio/x86_64/stable (runtime/org.kde.Platform/x86_64/5.12) found in remote flathub
Do you want to install it? [Y/n]: 

org.texstudio.TeXstudio permissions:
    ipc      network      x11      dri     file access [1]     dbus access [2]

    [1] host, xdg-config/kdeglobals:ro, xdg-run/dconf, ~/.config/dconf:ro
    [2] com.canonical.AppMenu.Registrar


        ID                                                             Arch     Branch   Remote    Download
 1. [✓] org.kde.Platform                                               x86_64   5.12     flathub   367.0 MB / 430.1 MB
 2. [✓] org.freedesktop.Platform.VAAPI.Intel                           x86_64   18.08    flathub     1.8 MB / 1.8 MB
 3. [✓] org.freedesktop.Platform.html5-codecs                          x86_64   18.08    flathub     3.0 MB / 3.3 MB
 4. [✓] org.kde.KStyle.Adwaita                                         x86_64   5.12     flathub     5.6 MB / 5.6 MB
 5. [✓] org.kde.PlatformTheme.QGnomePlatform.Sources                   x86_64   5.12     flathub    30.9 kB / 29.7 kB
 6. [✓] org.kde.PlatformTheme.QGnomePlatform                           x86_64   5.12     flathub   145.1 kB / 144.1 kB
 7. [✓] org.kde.WaylandDecoration.QGnomePlatform-decoration            x86_64   5.12     flathub    59.9 kB / 58.5 kB
 8. [✓] org.kde.WaylandDecoration.QGnomePlatform_decoration.Sources    x86_64   5.12     flathub     1.8 kB / 29.8 kB
 9. [✓] org.kde.Platform.Locale                                        x86_64   5.12     flathub    17.3 kB / 334.3 MB
10. [✗] org.texstudio.TeXstudio                                        x86_64   stable   flathub   446.4 MB / 1.9 GB

Error: While pulling app/org.texstudio.TeXstudio/x86_64/stable from remote flathub: Server returned HTTP 503
error: Failed to install org.texstudio.TeXstudio: While pulling app/org.texstudio.TeXstudio/x86_64/stable from remote flathub: Server returned HTTP 503
```

**Comment by mkrajnak** [comment] 2020-02-21 10:27
Same old, 

```
Looking for matches…
Required runtime for org.gnome.Eolie/x86_64/stable (runtime/org.gnome.Platform/x86_64/3.34) found in remote flathub

org.gnome.Eolie permissions:
    ipc	network	pulseaudio	wayland
    x11	dri	file access [1]	dbus access [2]
    bus ownership [3]

    [1] home, ~/.config/chrome, ~/.config/chromium, ~/.mozilla/firefox
    [2] org.freedesktop.secrets
    [3] org.gnome.Eolie.Proxy.*


 1.	   	org.freedesktop.Platform.GL.default	19.08	i	flathub	< 92.6 MB
 2.	   	org.freedesktop.Platform.openh264	19.08	i	flathub	< 593.4 kB
 3.	   	org.gnome.Eolie.Locale	stable	i	flathub	< 222.0 kB (partial)
 4.	   	org.gnome.Platform.Locale	3.34	i	flathub	< 322.2 MB (partial)
 5.	   	org.gnome.Platform	3.34	i	flathub	< 318.6 MB
 6.	   	org.gnome.Eolie	stable	i	flathub	< 12.9 MB



Installing 1/6…                                                                   
Installing 1/6… ▍                      2%
Installing 1/6… █████████▏            46%  2.3 MB/s
Installing 1/6… █████████▊            49%  3.7 MB/s
Installing 1/6… ██████████            50%  5.1 MB/s
Installing 1/6… ██████████▍           52%  6.9 MB/s
Installing 1/6… ███████████           55%  4.2 MB/s
Installing 1/6… ███████████▏          56%  4.9 MB/s
Installing 1/6… ███████████▍          57%  5.3 MB/s
Installing 1/6… ███████████▌          58%  3.9 MB/s
Installing 1/6… ███████████▊          59%  4.2 MB/s
Installing 1/6… ████████████          60%  4.6 MB/s
Installing 1/6… ████████████▍         62%  3.9 MB/s  00:02
Installing 1/6… ████████████▌         63%  4.2 MB/s  00:02
Installing 1/6… ████████████▌         63%  4.5 MB/s  00:02
Installing 1/6… ████████████▌         63%  4.9 MB/s  00:02
Installing 1/6… ████████████▌         63%  4.2 MB/s  00:02
Installing 1/6… ████████████▌         63%  4.4 MB/s  00:02
Installing 1/6… ████████████▌         63%  4.5 MB/s  00:02
Installing 1/6… ████████████▌         63%  3.9 MB/s  00:03
Installing 1/6… ████████████▊         64%  4.1 MB/s  00:03
Installing 1/6… █████████████         65%  4.3 MB/s  00:03
Installing 1/6… █████████████         65%  3.8 MB/s  00:03
Installing 1/6… █████████████         65%  3.8 MB/s  00:03
Installing 1/6… █████████████▏        66%  3.9 MB/s  00:03
Installing 1/6… █████████████▏        66%  4.0 MB/s  00:03
Installing 1/6… █████████████▏        66%  3.6 MB/s  00:04
Installing 1/6… █████████████▏        66%  3.7 MB/s  00:04
Installing 1/6… █████████████▏        66%  3.7 MB/s  00:04
Installing 1/6… █████████████▍        67%  3.4 MB/s  00:04
Installing 1/6… █████████████▍        67%  3.5 MB/s  00:04
Installing 1/6… █████████████▌        68%  3.6 MB/s  00:04
Installing 1/6… █████████████▌        68%  3.4 MB/s  00:04
Installing 1/6… █████████████▌        68%  3.5 MB/s  00:04
Installing 1/6… █████████████▊        69%  3.5 MB/s  00:04
Installing 1/6… █████████████▊        69%  3.3 MB/s  00:04
Installing 1/6… ██████████████        70%  3.4 MB/s  00:04
Installing 1/6… ██████████████▍       72%  3.5 MB/s  00:04
Installing 1/6… ██████████████▌       73%  3.6 MB/s  00:04
Installing 1/6… ██████████████▊       74%  3.4 MB/s  00:04
Installing 1/6… ███████████████       75%  3.5 MB/s  00:04
Installing 1/6… ███████████████▏      76%  3.6 MB/s  00:03
Installing 1/6… ███████████████▌      78%  3.5 MB/s  00:03
Installing 1/6… ███████████████▌      78%  3.5 MB/s  00:03
Installing 1/6… ███████████████▊      79%  3.6 MB/s  00:03
Installing 1/6… ████████████████      80%  3.4 MB/s  00:03
Installing 1/6… ████████████████▏     81%  3.4 MB/s  00:03
Installing 1/6… ████████████████▍     82%  3.5 MB/s  00:03
Installing 1/6… ████████████████▊     84%  3.6 MB/s  00:02
Installing 1/6… █████████████████▏    86%  3.4 MB/s  00:02
Installing 1/6… █████████████████▍    87%  3.5 MB/s  00:02
Installing 1/6… █████████████████▌    88%  3.6 MB/s  00:02
Installing 1/6… ██████████████████    90%  3.5 MB/s  00:01
Installing 1/6… ██████████████████▏   91%  3.6 MB/s  00:01
Installing 1/6… ██████████████████▍   92%  3.7 MB/s  00:01
Installing 1/6… ██████████████████▌   93%  3.5 MB/s  00:01
Installing 1/6… ██████████████████▊   94%  3.6 MB/s  00:01
Installing 1/6… ██████████████████▊   94%  3.6 MB/s  00:01
Installing 1/6… ██████████████████▊   94%  3.7 MB/s  00:01
Installing 1/6… ███████████████████▏  96%  3.5 MB/s  00:00
Installing 1/6… ███████████████████▏  96%  3.6 MB/s  00:00
Installing 1/6… ███████████████████▏  96%  3.7 MB/s  00:00
Installing 1/6… ███████████████████▏  96%  3.6 MB/s  00:00
Installing 1/6… ███████████████████▏  96%  3.6 MB/s  00:00
Installing 1/6… ███████████████████▏  96%  3.7 MB/s  00:00
Installing 1/6… ███████████████████▏  96%  3.5 MB/s  00:00
Installing 1/6… ███████████████████▍  97%  3.6 MB/s  00:00
Installing 1/6… ███████████████████▍  97%  3.6 MB/s  00:00
Installing 1/6… ███████████████████▍  97%  3.7 MB/s  00:00
Installing 1/6… ███████████████████▍  97%  3.6 MB/s  00:00
Installing 1/6… ███████████████████▍  97%  3.7 MB/s  00:00
Installing 1/6… ███████████████████▍  97%  3.7 MB/s  00:00
Installing 1/6… ███████████████████▍  97%  3.7 MB/s  00:00
Installing 1/6… ███████████████████▍  97%  3.8 MB/s  00:00
Installing 1/6… ███████████████████▍  97%  3.8 MB/s  00:00
Installing 1/6… ███████████████████▌  98%  3.7 MB/s  00:00
Installing 1/6… ███████████████████▌  98%  3.8 MB/s  00:00
Installing 1/6… ███████████████████▌  98%  3.8 MB/s  00:00
Installing 1/6… ███████████████████▌  98%  3.8 MB/s  00:00
Installing 1/6… ███████████████████▌  98%  3.7 MB/s  00:00
Installing 1/6… ███████████████████▌  98%  3.7 MB/s  00:00
Installing 1/6… ███████████████████▊  99%  3.8 MB/s  00:00
Installing 1/6… ███████████████████▊  99%  3.6 MB/s  00:00
Installing 1/6… ███████████████████▊  99%  3.7 MB/s  00:00
Installing 1/6… ███████████████████▊  99%  3.7 MB/s  00:00
Installing 1/6… ████████████████████ 100%  3.6 MB/s  00:00
Installing 2/6…                                                                   
Installing 2/6… █▌                     8%
Installing 2/6… ████████████████████ 100%
Installing 2/6… ████████████████████ 100%
Installing 3/6…                                                                   
Installing 3/6…                        0%
Installing 3/6… ████████████████████ 100%
Installing 4/6…                                                                   
Installing 4/6… ▍                      2%
Installing 4/6… ████████████████████ 100%
Installing 5/6…                                                                   
Installing 5/6… ██▍                   12%
Installing 5/6… ██▏                   11%
Installing 5/6… ██▏                   11%  495.0 kB/s
Installing 5/6… ██▏                   11%  582.1 kB/s
Installing 5/6… ██▏                   11%  702.6 kB/s
Installing 5/6… ██▏                   11%  366.1 kB/s
Installing 5/6… ██▏                   11%  372.3 kB/s
Installing 5/6… ██▏                   11%  248.5 kB/s
Installing 5/6… ██▏                   11%  248.9 kB/s
Err:
Warning: org.freedesktop.Platform.openh264 not installed                            

Error: While pulling runtime/org.gnome.Platform/x86_64/3.34 from remote flathub: Server returned HTTP 503
error: Failed to install org.gnome.Platform: While pulling runtime/org.gnome.Platform/x86_64/3.34 from remote flathub: Server returned HTTP 503
```

**Comment by jonathon-love** [comment] 2020-03-06 22:23
hi,

would it be possible to reopen this issue?

i occasionally have to install my own package from flathub, and am often surprise how many times i have to retry it, before i can get it to install. i was pretty glad when you guys mentioned new infrastructure, but this doesn't seem to have made a difference (in my limited experience).

i'm `org.jamovi.jamovi` if you'd like to try, it sounds like some (larger?) packages are impacted more than others.

with thanks

**Comment by dbarnett** [comment] 2020-03-07 17:54
Possibly related to same root cause as #505, where it may have been returning 404 responses when it's overloaded.

Definitely unresolved, and a major usability issue with flathub and flatpak. Would love to see the issue at least acknowledged.

**Comment by jonathon-love** [comment] 2020-03-09 05:43
i have found this to be very useful when installing things from flathub, in fact it should probably go in the installation instructions.

```
until flatpak install org.blah.Blah; do echo "Trying again"; sleep 2; done
```

you'll notice that between 503's, progress is actually being made, so this isn't redownloading the same content over and over.

cheers

**Comment by alexlarsson** [comment] 2020-03-09 10:39
I think we should figure out the exact cause of this, but also i filed https://github.com/ostreedev/ostree/issues/2022 about how ostree could auto-detect this and retry a few times.

**Comment by barthalion** [comment] 2020-03-09 14:48
I don't see any 503 errors on our load balancers. Around two hundred 503 errors were reported by Fastly to our stats box, but I don't think it's the issue we're talking about here as it sounds like something more common.

**Comment by jonathon-love** [comment] 2020-03-11 07:01
i don't know if this is related, but downloading test builds is remarkably slow too. it's quite typical to experience downloads at about 30k/s. combined with the 503s, a test download can take 3-5 hours to download.

**Comment by sudden6** [comment] 2020-03-14 13:24
I'm facing the same 503 error on our [Travis CI setup]( https://travis-ci.org/github/qTox/qTox/jobs/662207798#L1172) when downloading `runtime/org.kde.Sdk/x86_64/5.11`

**Comment by jonathon-love** [comment] 2020-03-14 21:32
@sudden6, you may actually find the 503's helpful on travis,

travis has a 50 minute job limit, and downloading a flatpak can take much longer than that.

if you're not running up against the time limit then just use:

`until flatpak install org.blah.Blah; do echo "Trying again"; sleep 2; done`

if you're running up against the time limit, the 503's will actually help you out. just list lots of installs like this:

```
 - flatpak install --user -y org.blah.Blah || true
 - flatpak install --user -y org.blah.Blah || true
 - flatpak install --user -y org.blah.Blah || true
 - flatpak install --user -y org.blah.Blah || true
 # 20-30 more, depending on how big your download is

 # then place this at the end
 - until flatpak install --user -y org.blah.Blah; do echo "Trying again"; sleep 2; done
```

by distributing the download over 30 separate 'jobs', no single job takes more than 50 minutes (where as if you just use a single `until` that counts as a single job). i honestly don't know how i'm going to install things on travis once they fix the 503's issue :P

once you've got it downloaded to travis, cache that sucker!

```
cache:
  directories:
    - $HOME/.local/share/flatpak/app/
```

and then have a script that only downloads if it's not in the cache:

```
if flatpak info --user org.blah.Blah 1>/dev/null 2>/dev/null ; then
    echo "already installed"
else
    echo "installing"
    flatpak install -y --user flathub org.blah.Blah
fi
```

i've found this works quite well.

cheers

**Comment by sudden6** [comment] 2020-03-15 15:47
@jonathon-love Thank you I arrived at the same conclusion, that downloading multiple times is probably the solution.

**Comment by barthalion** [comment] 2020-03-17 08:46
@sudden6 You should also consider upgrading flatpak to latest 1.4.x or 1.6.x releases. In previous releases there is a regression causing flatpak not to use static deltas.

**Comment by sisterfelicity** [comment] 2020-03-29 00:35
I'm having this same error trying to install flatpak MuseScore -- see the thread I started here: @https://github.com/flathub/org.musescore.MuseScore/issues/53

@jonathon-love, I'd like to try your "trying again" loop workaround, but I'm clearly getting it wrong ... please help with idiot-proof syntax? Thanks!

![image](https://user-images.githubusercontent.com/62124036/77837139-8eb94a00-7133-11ea-825d-a44e0e1b3a02.png)

**Comment by jonathon-love** [comment] 2020-03-29 07:48
ah yup, my bad, you're missing the repo (in this case `flathub`) in your call to flatpak install.

try this:

```
until flatpak install -y flathub org.musescore.MuseScore; do echo "Trying again"; sleep 2; done
```

**Comment by sisterfelicity** [comment] 2020-03-29 09:43
Thanks -- I tried it with and without prefixing "sudo", still missing something:

![Screenshot 2020-03-29 at 05 39 24](https://user-images.githubusercontent.com/62124036/77845822-c2ba5c80-717f-11ea-8920-1e6ac81a0927.png)

Tried replacing "do" with "sudo", and got the same syntax error but near 'done' instead of near 'do'

**Comment by jonathon-love** [comment] 2020-03-29 09:51
hmm, i'm slightly at a loss. that command works for me:

<img width="579" alt="Screen Shot 2020-03-29 at 20 50 24" src="https://user-images.githubusercontent.com/3240247/77846046-f9838780-71fe-11ea-9a1a-f250924ba792.png">

might have to await someone else's input.

**Comment by sisterfelicity** [comment] 2020-03-29 09:57
OK, thanks again. Patience is a virtue, they tell me.

**Comment by dbarnett** [comment] 2020-03-29 15:43
FWIW, we've digressed several levels from why the server craps out sometimes to troubleshooting a particular invocation scenario of a hacky retry script.

Flathub devs, please consider putting some more attention into fixing the actual 503 problem. If there is a way, it'd be win-win: I suspect having people loop and retry will also not be kind to your servers.

**Comment by barthalion** [comment] 2020-04-16 08:43
The issue is gone now. Nodes in our load balancer were not keeping up with traffic from CDN; they were replaced with new SSD-backed hosts and number of 503s in CDN logs is down to zero.

**Closed by barthalion** 2020-04-16 08:43 UTC
