### ISSUE TITLE
Build fails when trying to download git submodule

### ISSUE THREAD

**Issue by junrrein** [flathub/flathub#1078] opened 2019-07-20 21:28 UTC
Hi there,

My application, PDF Slicer, uses Git submodules for a couple of utility libraries (which is kind of usual in C++ land).

My last couple of builds are [failing](https://flathub.org/builds/#/builders/19/builds/676) when trying to clone a git submodule. I can clone that submodule fine manually, and I can successfully build the Flatpak package locally.

Was there a change in Flathub policy forbidding the use of git submodules? I could understand the rationale, if that were the case. I can convert the use of git submodules to a source copy of the repos in my repo. But I don't know if this is happening due to a change of policy or due to a bug.

**Comment by bilelmoussaoui** [comment] 2019-08-02 17:01
Nothing has changed as far as I know. I would suggest using a tarball instead. Tarball's here on github include the submodules.

**Comment by junrrein** [comment] 2019-08-02 19:50
@bilelmoussaoui 

The tarballs that Github generates for my app don't seem to include submodules. [Here is the latest release](https://github.com/junrrein/pdfslicer/releases/tag/v1.7.3) so you can check yourself if you want (the submodules are in `third-party/fmtlib`, `third-party/GSL` and `third-party/range-v3`).

Regardless, I just tried a rebuild to see if it was a transient Flathub issue, but it doesn't seem to be. For reference, [here](https://github.com/flathub/com.github.junrrein.PDFSlicer/pull/22) is the pull request to update the app to the latest version, and [here](https://github.com/flathub/com.github.junrrein.PDFSlicer/pull/21) it the pull request to update to the previous version. Both versions ship the same submodules (at the same fixed tag).

**Comment by hfiguiere** [comment] 2019-09-29 15:05
This thing is that in #23 we use a tree that has already been build. So this is a regression, either with the infra or the SDK.

**Comment by TingPing** [comment] 2019-09-29 22:05
This should have been fixed in the buildbot last week...

**Comment by junrrein** [comment] 2019-09-29 22:24
@hfiguiere 

I think you meant to link https://github.com/flathub/com.github.junrrein.PDFSlicer/pull/23.

**Comment by hfiguiere** [comment] 2019-09-30 00:47
Yes, I meant that. Fixed.

**Comment by hfiguiere** [comment] 2019-09-30 00:49
> Yes this is a regression, and I thought was fixed in the buildbot last week...

Last week the problem was with submodules in the flathub repository (like shared-modules). This one if I understand is that the submodules from the source tree are ignored.

**Comment by bochecha** [comment] 2019-12-01 21:35
> > Yes this is a regression, and I thought was fixed in the buildbot last week...
> 
> Last week the problem was with submodules in the flathub repository (like shared-modules). This one if I understand is that the submodules from the source tree are ignored.

The submodules from the sources of a module are supposed to be fetched by flatpak-builder when it downloads the sources, before building.

**Comment by barthalion** [comment] 2019-12-02 07:47
I'm not sure what the original issue was about; the thing in September was indeed a regression in buildbot configuration but it was fixed since then.

**Closed by barthalion** 2019-12-02 07:47 UTC

**Comment by barthalion** [comment] 2019-12-02 07:50
Current [build failure](https://flathub.org/builds/#/builders/7/builds/922) indicates repository corruption which may be fixed by playing with `disable-fsckobjects` and `disable-shallow-clone`.

**Comment by junrrein** [comment] 2019-12-02 22:54
@barthalion Using `disable-shallow-clone` did the trick. Thanks a lot!
