### ISSUE TITLE
Add flathub runtime platform für Mac und Windows.

### ISSUE THREAD

**Issue by chiddekel** [flathub/flathub#3934] opened 2023-02-25 08:13 UTC

**Comment by JakobDev** [comment] 2023-02-26 10:39
Flatpak works only on Linux

**Comment by chiddekel** [comment] 2023-02-27 07:09
The whole idea behind it is to use for example some later on Mac and Windows - maybe based on docker to provide the some like full runtime.

**Comment by iavael** [comment] 2023-03-17 06:53
@chiddekel if you want to run flatpaks on windows just use wsl2, it gonna provide what you want.

**Comment by iavael** [comment] 2023-03-17 13:30
@chiddekel flatpak depends heavily on linux kernel API and it's isolation mechanisms. One way or another you can only run flatpaks in linux environment. So if you want to run flatpaks on Windows or Mac you must use linux VM.
Integration of such linux virtual machine with host OS may vary: WSL2 gives the best expirience OOTB but in other cases you usually have to solve the problem yourself and combine hypervisor to run linux VM with X11 server for you host OS in most suitable way for your case.

Creating universal solution to seamlessly run linux VM with apps and demonstrate UI on host OS is not a simple task and it doesn't look like to be in scope of flathub project or even flatpak (for WSL2 it took from Microsoft couple of years of a hard of work of several developer teams and bunch of changes in windows source code to make WSL2 as we see it today, so it's not an easy problem that flatpak or flathub dev teams can quickly solve without loosing focus on their main project).

But the good news is that creating ad-hoc setup without 3D acceleration for you specific needs isn't too hard, so you can try to create it as a weekend exercise (just take X11 server for macos or windows, setup linux VM under any hypervisor you like, run apps in VM with DISPLAY envvar pointing to you host X11 server).

**Comment by chiddekel** [comment] 2023-03-18 14:25
> @chiddekel flatpak depends heavily on linux kernel API and it's isolation mechanisms. One way or another you can only run flatpaks in linux environment. So if you want to run flatpaks on Windows or Mac you must use linux VM. Integration of such linux virtual machine with host OS may vary: WSL2 gives the best expirience OOTB but in other cases you usually have to solve the problem yourself and combine hypervisor to run linux VM with X11 server for you host OS in most suitable way for your case.
> 
> Creating universal solution to seamlessly run linux VM with apps and demonstrate UI on host OS is not a simple task and it doesn't look like to be in scope of flathub project or even flatpak (for WSL2 it took from Microsoft couple of years of a hard of work of several developer teams and bunch of changes in windows source code to make WSL2 as we see it today, so it's not an easy problem that flatpak or flathub dev teams can quickly solve without loosing focus on their main project).
> 
> But the good news is that creating ad-hoc setup without 3D acceleration for you specific needs isn't too hard, so you can try to create it as a weekend exercise (just take X11 server for macos or windows, setup linux VM under any hypervisor you like, run apps in VM with DISPLAY envvar pointing to you host X11 server).

It's only depends what are goals. So you write about some challenges. But isn't say that any of this challenge occure. Docker desktop for windows -  https://www.docker.com/products/docker-desktop/ solve all montoined - so we can make it like base to make flatpak runtime on windows or even Mac - https://docs.docker.com/desktop/install/mac-install/

**Comment by iavael** [comment] 2023-03-18 22:26
@chiddekel sure, it depends what are the goals. The problem is that goal of flatpak and flathub is not creating alternative to wsl2 (transparent mechanism to run linux programs with gui and sound) for windows and mac.
Docker is commercial company and they can afford to run multiple different projects: moby, containerd, hyperkit and many others. While flatpak's main purpose is, you know flatpak itself, and flathub's - application store.

You essentialy want another (and quite ambitious) "openwsl" project that flatpak would be able to use to run apps on other OSes. And on the top of that you are demanding this project from flathub project which is different from flatpak.

**Comment by chiddekel** [comment] 2023-03-19 08:42
> @chiddekel sure, it depends what are the goals. The problem is that goal of flatpak and flathub is not creating alternative to wsl2 (transparent mechanism to run linux programs with gui and sound) for windows and mac. Docker is commercial company and they can afford to run multiple different projects: moby, containerd, hyperkit and many others. While flatpak's main purpose is, you know flatpak itself, and flathub's - application store.
> 
> You essentialy want another (and quite ambitious) "openwsl" project that flatpak would be able to use to run apps on other OSes. And on the top of that you are demanding this project from flathub project which is different from flatpak.
> 
> Also docker for windows/mac doesn'n solve most important problems (passing graphics and sound) because it focuses on running non-interactive load like server software while flatpak mostly runs interactive programs with gui and sound. And moreover docker-for-win/mac is closed source.

So  with docker desktop for Linux mac and Windows is make good frotnted support audio and display.

**Comment by chiddekel** [comment] 2023-03-19 08:44
This can be done ✅ with ask if docker company it's interesting in making Support for flatpak desktop as backend and frotnted of store and runtime for app.

**Comment by barthalion** [comment] 2023-03-25 16:21
I'm closing this as it's out of scope for Flathub.

**Closed by barthalion** 2023-03-25 16:21 UTC
