### ISSUE TITLE
Can't use flathub beta to publish "development" version

### ISSUE THREAD

**Issue by hadess** [flathub/flathub#2821] opened 2022-02-02 19:11 UTC
When trying to build a `org.gnome.Totem` development profile build, which builds as `org.gnome.Totem.Devel`, with a visible "roadworks" icon, and separate configuration, I got an error during publication because:
```
43:48 failed 'stat builddir/*/share/app-info/xmls/org.gnome.Totem.xml.gz' (failure) FAILURE
```

There are 2 problems here, the first one being that the application is defined as `org.gnome.Totem.Devel` in the manifest, so surely the build bot shouldn't have to go all the way to the end of the build before figuring out that it won't be able to publish the application.

The second is that it would be disappointing to not be able to publish WIP application in a beta channel under a different ID, allowing for faster bug reporting, while keeping a working version side-by-side, without resorting to the command-line past the installation. The application in question cannot easily ship what it ships in Flathub as part of its GNOME nightly Flatpak builds.

**Comment by hadess** [comment] 2022-02-04 10:13
@barthalion worked around this specific problem by creating a separate repo (https://github.com/flathub/org.gnome.Totem.Devel) that only has a beta branch. This is a useful work-around, but even if you can setup a branch on the original org.gnome.Totem repo to track the devel repo, this will throw off things like merge requests which will only be able to target the origin remote.

Perhaps a "app-id-beta-suffix" configuration in flathub.json could be the right entry point?

**Comment by bbhtt** [comment] 2024-07-10 15:50
Dupe of https://github.com/flathub/flathub/issues/1138

**Closed by bbhtt** 2024-07-10 15:50 UTC
Labels: discussion
