### ISSUE TITLE
Can't install debug kde sdk

### ISSUE THREAD

**Issue by Bleuzen** [flathub/flathub#2725] opened 2022-01-03 23:11 UTC
I currently try to debug a crash on Carla, see:
https://github.com/flathub/studio.kx.carla/pull/17#issuecomment-1001727421

But when I want to install the kde sdk debug symbols, I get:

```
~ ❯ LANG=C flatpak install --user org.kde.Sdk.Debug//5.15-21.08                                                                                                                                                                        
Looking for matches?


        ID                         Branch              Op          Remote          Download
 1. [?] org.kde.Sdk.Debug          5.15-21.08          i           flathub         1.0?kB / 3.7?GB

Error: Failed to read commit 751b9edecd09583964df2d504d6276414af02bb864c3d5775e78a45bbce36660: No such metadata object cc743e0d516d246866ecf5dc6d9437004a19b9c85cadb8b0c034c4df09dc90c6.dirtree
error: Failed to install org.kde.Sdk.Debug: Failed to read commit 751b9edecd09583964df2d504d6276414af02bb864c3d5775e78a45bbce36660: No such metadata object cc743e0d516d246866ecf5dc6d9437004a19b9c85cadb8b0c034c4df09dc90c6.dirtree
```

**Comment by barthalion** [comment] 2022-01-04 09:13
Can you try with `--no-static-deltas`?

**Comment by Bleuzen** [comment] 2022-01-04 13:59
@barthalion 
> Can you try with `--no-static-deltas`?

still doesn't work, same error

**Comment by Cuperino** [comment] 2022-01-08 00:11
I'm having the same error as @Bleuzen, with the exact same commit IDs. Think this might have been caused by the fact that I had both the `kde-runtimes` and `flathub` repositories installed. Don't know from which repository org.kde.Sdk.Debug attempted to install previously.

Tried removing the `kde-runtimes` repository, removing all installed KDE runtimes (which did not include `org.kde.Sdk.Debug` because it never installed), also tried running `flatpak repair`, and performing the install with `--no-static-deltas`.

I'm running KDE neon Testing Edition as the host system, and the install was not performed using the `--user` flag.

**Comment by Bleuzen** [comment] 2022-01-15 15:50
Errors now looking different. Sometimes it downloads something but fails at some point.

```
~ ❯ flatpak install org.kde.Sdk.Debug//5.15-21.08                                                               [1] 
Looking for matches…


        KENNUNG                    Zweig               Op          Remote          Download
 1. [✗] org.kde.Sdk.Debug          5.15-21.08          i           flathub         68,8 MB / 3,7 GB

Error: Während des Holens von runtime/org.kde.Sdk.Debug/x86_64/5.15-21.08 von der entfernten Quelle flathub: Server returned status 404: Not Found
Fehler: Failed to installieren org.kde.Sdk.Debug: Während des Holens von runtime/org.kde.Sdk.Debug/x86_64/5.15-21.08 von der entfernten Quelle flathub: Server returned status 404: Not Found

~ ❯ flatpak install org.kde.Sdk.Debug//5.15-21.08                                                             [1] 9s
Looking for matches…


        KENNUNG                    Zweig               Op          Remote          Download
 1. [✗] org.kde.Sdk.Debug          5.15-21.08          i           flathub         1,0 kB / 3,7 GB

Error: Error pulling from repo: While pulling runtime/org.kde.Sdk.Debug/x86_64/5.15-21.08 from remote flathub: fsck 4769649decf76d6d19b6b0c1c72f3098a036e61e2a33891bc6089a727ab2aa25.dirtree: No such metadata object 4769649decf76d6d19b6b0c1c72f3098a036e61e2a33891bc6089a727ab2aa25.dirtree
Fehler: Failed to installieren org.kde.Sdk.Debug: Error pulling from repo: While pulling runtime/org.kde.Sdk.Debug/x86_64/5.15-21.08 from remote flathub: fsck 4769649decf76d6d19b6b0c1c72f3098a036e61e2a33891bc6089a727ab2aa25.dirtree: No such metadata object 4769649decf76d6d19b6b0c1c72f3098a036e61e2a33891bc6089a727ab2aa25.dirtree

~ ❯ LANG=C flatpak install org.kde.Sdk.Debug//5.15-21.08                                                      [1] 1s
Looking for matches?


        ID                         Branch              Op          Remote          Download
 1. [?] org.kde.Sdk.Debug          5.15-21.08          i           flathub         98.9?MB / 3.7?GB

Error: While pulling runtime/org.kde.Sdk.Debug/x86_64/5.15-21.08 from remote flathub: Server returned status 404: Not Found
error: Failed to install org.kde.Sdk.Debug: While pulling runtime/org.kde.Sdk.Debug/x86_64/5.15-21.08 from remote flathub: Server returned status 404: Not Found

~ ❯ LANG=C flatpak install org.kde.Sdk.Debug//5.15-21.08                                                     [1] 13s
Looking for matches?


        ID                         Branch              Op          Remote          Download
 1. [?] org.kde.Sdk.Debug          5.15-21.08          i           flathub         140.3?MB / 3.7?GB

Error: While pulling runtime/org.kde.Sdk.Debug/x86_64/5.15-21.08 from remote flathub: Server returned status 404: Not Found
error: Failed to install org.kde.Sdk.Debug: While pulling runtime/org.kde.Sdk.Debug/x86_64/5.15-21.08 from remote flathub: Server returned status 404: Not Found
```

**Comment by hfiguiere** [comment] 2022-01-22 15:13
Same here. see #2788

**Comment by hfiguiere** [comment] 2022-01-23 04:59
@barthalion would a rebuild of the runtime for `aarch64` solve the problem?

**Comment by Bleuzen** [comment] 2022-02-04 15:34
Hi @barthalion , any progress on this?
Who is even responsible for it, do we need to contact KDE devs?

**Comment by hfiguiere** [comment] 2022-02-06 18:20
Now I'm getting plain 404:
```
 1. [✗] org.kde.Sdk.Debug          5.15-21.08          i           flathub         98.6 MB / 2.4 GB

Error: While pulling runtime/org.kde.Sdk.Debug/aarch64/5.15-21.08 from remote flathub: Server returned status 404: Not Found
error: Failed to install org.kde.Sdk.Debug: While pulling runtime/org.kde.Sdk.Debug/aarch64/5.15-21.08 from remote flathub: Server returned status 404: Not Found
```

**Comment by bbhtt** [comment] 2024-07-10 15:30
This seems solved now:

```
 flatpak install --user flathub org.kde.Sdk.Debug//5.15-21.08                                      
Looking for matches…

Info: runtime org.kde.Sdk.Debug branch 5.15-21.08 is end-of-life, with reason:
   We strongly recommend moving to the latest stable version of the Platform and SDK


        ID                         Branch              Op          Remote          Download
 1. [✓] org.kde.Sdk.Debug          5.15-21.08          i           flathub         3.9 GB / 4.0 GB

Installation complete.
```

and the runtime is EOL so closing. Please open new issues if you see this again on a non EOL runtime.

**Closed by bbhtt** 2024-07-10 15:30 UTC
Labels: infrastructure
