### ISSUE TITLE
Better icon and description for flathub.flatparepo

### ISSUE THREAD

**Issue by kalev** [flathub/flathub#885] opened 2019-03-04 12:32 UTC
When opening flathub.flatpakrepo in gnome-software, it currently looks like this:

https://kalev.fedorapeople.org/flathub-flatpakrepo.png

Would be nice to have a higher res icon than the current 32x32 px one, and also a longer description that explains a bit what this repo is (and with full sentence punctuation, so it ends with a full stop.)

**Comment by jimmac** [comment] 2019-03-04 14:05
The logo on the website is SVG -- https://flathub.org/assets/themes/flathub/flathub-logo-toolbar.svg

To be sure here's a 64px nominal size version of it:
http://jimmac.musichall.cz/stuff/flathub-software-logo.svg

**Comment by bilelmoussaoui** [comment] 2019-03-04 14:45
Duplicate of this https://github.com/flathub/flathub/issues/468

**Comment by matthiasclasen** [comment] 2019-03-04 14:53
where does the flatpakrepo file live in git ?

**Comment by allanday** [comment] 2019-03-12 11:31
A quick draft of some more expanded description text:

"Flathub is a leading provider of apps for Linux desktops. It provides access to hundreds of apps, and is growing all the time. 

 - [Browse the apps online](https://flathub.org/apps) or from your desktop app center.
 - The apps provided by Flathub are constantly updated, so you get the latest versions.
 - Thanks to the power of Flatpak, Flathub can be used on any Linux distribution.

Flathub is only possible thanks to the work of the community which maintain it. We are also extremely grateful for the support we've received from a number of organisations, including  Codethink, Fastly, Mythic Beasts and Scaleway."

**Comment by kalev** [comment] 2019-03-12 11:53
> * [Browse the apps online](https://flathub.org/apps) or from your desktop app center.

I'd leave this part out. It seems a bit weird to talk about browsing apps online when one is adding a repo to be able to browse them locally. Also, gnome-software doesn't handle wiki text links so it's going to look bad.

Otherwise looks much better than the current text to me! Thanks Allan.

**Comment by allanday** [comment] 2019-03-12 15:33
> I'd leave this part out.

Yes but bullet points look better in threes! A prize for someone who comes up with an alternative.

**Comment by allanday** [comment] 2019-03-13 15:51
For the bullet points, maybe:

```
 - Apps are constantly updated, so you always get the latest version
 - Efficient downloads and disk storage, thanks to Flatpak
 - Usable on any Linux distribution
```

**Comment by alexlarsson** [comment] 2019-04-23 14:00
Hmm, the comment is just a single line in a keyfile atm. I wonder if we can do multi-line stuff in that...

**Comment by matthiasclasen** [comment] 2019-04-23 15:12
there's a separate field for multi-line descriptions, no ?

**Comment by alexlarsson** [comment] 2019-04-23 15:20
I guess you can just '\n' escape them

**Comment by matthiasclasen** [comment] 2019-04-23 16:03
#define FLATPAK_REPO_DESCRIPTION_KEY "Description"

and yes, \n works

**Comment by razzeee** [comment] 2023-06-18 12:25
The file that will need to change is located here: https://flathub.org/repo/flathub.flatpakrepo

**Comment by razzeee** [comment] 2024-02-14 15:35
I guess this would be the same work as https://github.com/flathub/flathub/issues/4258

**Comment by bbhtt** [comment] 2024-02-15 03:14
Yea let's close this. It should be updated to the new one.

**Closed by bbhtt** 2024-02-15 03:14 UTC
Labels: infrastructure
