### ISSUE TITLE
Build check requires "remote" icon even though icons are included

### ISSUE THREAD

**Issue by FoxxMD** [flathub/flathub#4216] opened 2023-06-07 14:33 UTC
Building [this minor release bump](https://github.com/flathub/io.github.foxxmd.multiscrobbler/pull/2) is causing the build check to fail on [Check for 128x128 icon](https://buildbot.flathub.org/#/builders/6/builds/45709) -- it looks like its requiring 

```xml
<icon type="remote" ...>
```
in the flathub manifest. But my build manifest _does_ [include icons](https://github.com/flathub/io.github.foxxmd.multiscrobbler/blob/bump-release/io.github.foxxmd.multiscrobbler.yml#L50), at 512x512 and 128x128 (through svg). They are generated in the manifest like:

```xml
   <icon type="cached" height="64" width="64">io.github.foxxmd.multiscrobbler.png</icon>
   <icon type="cached" height="128" width="128">io.github.foxxmd.multiscrobbler.png</icon>
```

This was not an issue when I initially pushed my app back in march and I have not made any signficant changes for this build. Additionally, `flatpak-builder` builds without issues locally.

What can I do to resolve this?

**Comment by hfiguiere** [comment] 2023-06-07 15:37
The appstream file says: `<component type="console-application">` which I believe is the source of regression

**Comment by hfiguiere** [comment] 2023-06-07 15:38
(we recently - yesterday - changed the appstream tooling)

**Comment by razzeee** [comment] 2023-06-07 16:15
Should probably be reported over at https://github.com/ximion/appstream then?

**Comment by hfiguiere** [comment] 2023-06-07 17:04
it's a regression here since it worked. Also I'm just speculating this is the problem.

**Comment by bbhtt** [comment] 2024-02-17 05:22
Hi @FoxxMD, can you please fix this error reported and trigger a build https://buildbot.flathub.org/#/builders/6/builds/100593 ? That'll compose the metadata with libappstream and show the current state.

The error means you need to add a provides tag with a binary child tag See https://docs.flathub.org/docs/for-app-authors/metainfo-guidelines/#provides

**Comment by bbhtt** [comment] 2024-03-23 14:43
closing as solved https://github.com/flathub/io.github.foxxmd.multiscrobbler/pull/14 is no longer failing on the same thing. This was probably solved with the libappstream migration.

**Closed by bbhtt** 2024-03-23 14:43 UTC
Labels: libappstream
