### ISSUE TITLE
Flathub requires applications to break Freedesktop icon naming specification

### ISSUE THREAD

**Issue by Be-ing** [flathub/flathub#2463] opened 2021-08-15 22:45 UTC
The [Freedesktop icon naming specification](https://specifications.freedesktop.org/icon-naming-spec/icon-naming-spec-latest.html#guidelines) says:

> An application must either use a generic application icon name provided by this specification, or install an icon named the same as the executable for running the application.

But Flathub [demands reverse DNS for icon file names](https://flathub.org/builds/#/builders/8/builds/6717):

```
Running appstream-compose
FB: Running: flatpak build --die-with-parent --nofilesystem=host /srv/buildbot/worker/build-x86_64-2/build/.flatpak-builder/rofiles/rofiles-FrBg2z appstream-compose --prefix=/app --origin=flatpak --basename=org.mixxx.Mixxx org.mixxx.Mixxx
Processing application org.mixxx.Mixxx
Error loading desktop file: Failed to find icon: Failed to find icon org.mixxx.Mixxx
Error: ERROR: appstream-compose failed: Child process exited with code 1
```

Further context:
https://github.com/mixxxdj/mixxx/pull/4204
https://github.com/flathub/org.mixxx.Mixxx/pull/35

**Comment by vchernin** [comment] 2021-08-16 05:45
I am not an expert, but I don't think this is anything specific to Flathub, but to Flatpak in general.

Flatpak expects the icon name to follow the Application ID. In Flatpak the Application ID must be reverse-DNS style. [Relevant docs](https://docs.flatpak.org/en/latest/conventions.html#application-ids).

As to whether this contradicts the Freedesktop icon naming specification... I'm not sure.

**Comment by Be-ing** [comment] 2021-08-16 14:40
You're right, I can reproduce this with flatpak-builder locally:

```
Finishing app
Exporting share/applications/org.mixxx.Mixxx.desktop
Exporting share/icons/hicolor/scalable/apps/org.mixxx.Mixxx.svg
Not exporting share/icons/hicolor/32x32/apps/mixxx.png, non-allowed export filename
Exporting share/icons/hicolor/32x32/apps/org.mixxx.Mixxx.png
Exporting share/icons/hicolor/64x64/apps/org.mixxx.Mixxx.png
Exporting share/icons/hicolor/128x128/apps/org.mixxx.Mixxx.png
Exporting share/icons/hicolor/256x256/apps/org.mixxx.Mixxx.png
Exporting share/icons/hicolor/512x512/apps/org.mixxx.Mixxx.png
```

I reported the [issue](https://github.com/flatpak/flatpak/issues/4368) upstream to Flatpak.

**Comment by barthalion** [comment] 2021-08-16 16:16
Just a heads-up, but it's clear to me it will be closed as *not a bug* in Flatpak repo. Exporting assets (i.e. icons, desktop files, mime types, appdata) has to be bound to app ID to ensure uniqueness. If anything, icon specification should be updated to mention reverse DNS like desktop file specification does.

**Closed by barthalion** 2021-08-16 16:16 UTC

**Comment by barthalion** [comment] 2021-08-16 16:21
And to expand upon – Flatpak was designed and written by people who mostly wrote these specifications in the first place. So it's probably safe to assume the specification is behind reality rather than flatpak being wrong here.

**Comment by Be-ing** [comment] 2021-08-16 16:39
That's what I thought, but I encountered pushback changing the icon names upstream in Mixxx because it contradicts the old icon naming specification.
