### ISSUE TITLE
Installing Jellyfin fails, copy-pasting instructions from the docs.

### ISSUE THREAD

**Issue by NaturalBornCamper** [flathub/flathub#3234] opened 2022-06-05 19:28 UTC
Tried installing Jellyfin media player from the official instructions for Raspberry Pi 4 (copy-pasted):

1. Install flatpak: https://flatpak.org/setup/Raspberry%20Pi%20OS
2. Reboot and install Jellyfin: https://flathub.org/apps/details/com.github.iwalton3.jellyfin-media-player

But getting the error
`error: Nothing matches com.github.iwalton3.jellyfin-media-player in remote flathub`

Going to install using the Jellyfin deb pacakges from Github instead, but thought I would mention this here so you know either the docs are wrong or the package is not working.

**Comment by rusty-snake** [comment] 2022-06-05 19:45
Duplicate of https://github.com/flathub/com.github.iwalton3.jellyfin-media-player/issues/2

Most important question:

> Do you run a 64-bits (aarch64) OS on the Raspberry Pi?

> Just to clarify, and it's mentionned on the setup page you list: if you run the 32-bits OS (the default from Raspberry Pi foundation, as they hide the 64-bits version) you are unlikely to have proper support. This application flatpak was created after armv7 was dropped so it doesn't exist.

**Closed** 2022-06-06 06:54 UTC
